// src/components/ComparePanel.tsx
import { useEffect, useState } from 'react';
import { RefreshCw } from 'lucide-react';
import { cn } from '@/lib/utils';

// Loads /benchmark-results.json written by demo/compare.py and renders a
// side-by-side unidb vs Postgres comparison with bar charts. Static file
// fetch (not an engine REST call — `demo/compare.py` writes it to `public/`).

interface QueryResult {
  label: string;
  unidb_ms: number | null;
  postgres_ms?: number | null;
  ratio?: number | null;
}
interface BenchmarkData {
  size: string;
  n_cust?: number;
  n_ord?: number;
  run_at: string;
  unidb_url: string;
  postgres_dsn?: string;
  summary?: { unidb_total_ms: number; postgres_total_ms: number; ratio?: number | null };
  queries: QueryResult[];
}

function ratioLabel(r: number | null | undefined) {
  if (r == null) return '';
  if (r < 0.95) return `unidb ${(1 / r).toFixed(2)}× faster`;
  if (r > 1.05) return `postgres ${r.toFixed(2)}× faster`;
  return 'roughly equal';
}
function ratioClass(r: number | null | undefined) {
  if (r == null) return 'text-text-muted';
  if (r < 0.8) return 'text-ok';
  if (r < 0.95) return 'text-ok/70';
  if (r > 1.25) return 'text-error';
  if (r > 1.05) return 'text-error/70';
  return 'text-text-muted';
}
function fmt(ms: number | null | undefined) {
  if (ms == null) return '—';
  return ms < 1000 ? `${ms.toFixed(1)} ms` : `${(ms / 1000).toFixed(2)} s`;
}
function relTime(iso: string) {
  const diff = Date.now() - new Date(iso).getTime();
  if (diff < 60000) return `${Math.floor(diff / 1000)}s ago`;
  if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`;
  return new Date(iso).toLocaleTimeString();
}

export function ComparePanel() {
  const [data, setData] = useState<BenchmarkData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function loadResults() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/benchmark-results.json', { cache: 'no-store' });
      if (res.status === 404) {
        setData(null);
      } else if (!res.ok) {
        setError(`HTTP ${res.status}`);
      } else {
        setData(await res.json());
      }
    } catch (e: any) {
      setError(e?.message ?? String(e));
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadResults();
  }, []);

  const maxMs = data?.queries?.length ? Math.max(...data.queries.flatMap((q) => [q.unidb_ms ?? 0, q.postgres_ms ?? 0])) : 1;
  const barPct = (ms: number | null | undefined) => Math.min(100, ((ms ?? 0) / (maxMs || 1)) * 100);

  return (
    <div className="flex max-w-[960px] flex-col gap-4.5 text-md">
      <div className="flex items-center justify-between">
        <div className="flex flex-wrap items-baseline gap-2.5">
          <h2 className="m-0 text-lg font-medium text-foreground">unidb vs Postgres</h2>
          {data && (
            <>
              <span className="rounded-full bg-brand-subtle px-2 py-0.5 text-xs font-semibold text-brand">
                {data.size} · {data.n_cust?.toLocaleString()} customers · {data.n_ord?.toLocaleString()} orders
              </span>
              <span className="text-xs text-text-muted">run {relTime(data.run_at)}</span>
            </>
          )}
        </div>
        <button className="flex items-center gap-1.5 rounded-md border border-border bg-secondary px-2.5 py-1 text-sm hover:border-border-strong" onClick={loadResults}>
          <RefreshCw className="size-3" /> Refresh
        </button>
      </div>

      {loading ? (
        <p className="p-10 text-center text-md text-text-light">Loading…</p>
      ) : error ? (
        <div className="rounded-lg border border-error/40 bg-error-subtle px-4 py-3 text-md text-error">Error loading results: {error}</div>
      ) : !data ? (
        <div className="rounded-lg border border-border bg-card p-5 leading-relaxed">
          <strong>No results yet.</strong> Run the comparison script to generate data:
          <pre className="mt-2.5 rounded-md bg-secondary p-2.5 text-sm">
            pip3 install psycopg2-binary{'\n'}python3 demo/compare.py --size 10k
          </pre>
          Then click <em>Refresh</em> above.
        </div>
      ) : (
        <>
          {data.summary && (
            <div className="flex flex-wrap items-center gap-4.5">
              <div className="min-w-40 rounded-lg border border-border border-l-4 border-l-brand bg-card p-3.5 px-5">
                <div className="text-xs tracking-wide text-text-muted uppercase">unidb</div>
                <div className="my-1 text-2xl font-bold">{fmt(data.summary.unidb_total_ms)}</div>
                <div className="text-xs text-text-muted">total across {data.queries.length} queries</div>
              </div>
              <div className="text-lg font-bold text-text-muted">vs</div>
              <div className="min-w-40 rounded-lg border border-border border-l-4 border-l-[#336791] bg-card p-3.5 px-5">
                <div className="text-xs tracking-wide text-text-muted uppercase">PostgreSQL 16</div>
                <div className="my-1 text-2xl font-bold">{fmt(data.summary.postgres_total_ms)}</div>
                <div className="text-xs text-text-muted">total across {data.queries.length} queries</div>
              </div>
              {data.summary.ratio != null && (
                <div className={cn('text-md font-semibold', ratioClass(data.summary.ratio))}>
                  {ratioLabel(data.summary.ratio)}
                  <div className="text-xs font-normal text-text-muted">overall</div>
                </div>
              )}
            </div>
          )}

          <div className="flex flex-col gap-3.5">
            {data.queries.map((q, i) => (
              <div key={i} className="rounded-lg border border-border bg-card p-3.5">
                <div className="mb-2 font-semibold">{q.label}</div>
                <div className="flex flex-col gap-1.5">
                  <div className="flex items-center gap-2">
                    <span className="w-[68px] shrink-0 text-[10px] font-bold tracking-wide text-brand uppercase">unidb</span>
                    <div className="h-3 flex-1 overflow-hidden rounded-sm bg-secondary">
                      <div className="h-full rounded-sm bg-brand opacity-80 transition-[width]" style={{ width: `${barPct(q.unidb_ms)}%` }} />
                    </div>
                    <span className="w-[70px] shrink-0 text-right text-sm tabular-nums">{fmt(q.unidb_ms)}</span>
                  </div>
                  {q.postgres_ms != null && (
                    <div className="flex items-center gap-2">
                      <span className="w-[68px] shrink-0 text-[10px] font-bold tracking-wide text-[#336791] uppercase">postgres</span>
                      <div className="h-3 flex-1 overflow-hidden rounded-sm bg-secondary">
                        <div className="h-full rounded-sm bg-[#336791] opacity-80 transition-[width]" style={{ width: `${barPct(q.postgres_ms)}%` }} />
                      </div>
                      <span className="w-[70px] shrink-0 text-right text-sm tabular-nums">{fmt(q.postgres_ms)}</span>
                    </div>
                  )}
                </div>
                {q.ratio != null && <div className={cn('mt-1.5 text-xs font-semibold', ratioClass(q.ratio))}>{ratioLabel(q.ratio)}</div>}
              </div>
            ))}
          </div>

          <div className="border-t border-border pt-2 text-xs leading-loose text-text-muted">
            unidb @ <code className="font-mono">{data.unidb_url}</code>
            {data.postgres_dsn && (
              <>
                {' '}
                · postgres DSN: <code className="font-mono">{data.postgres_dsn}</code>
              </>
            )}
            <br />
            <span>
              Timings are browser/script round-trip (network included). Run <code>python3 demo/compare.py --size 50k</code> to refresh.
            </span>
          </div>
        </>
      )}
    </div>
  );
}

// src/lib/ComparePanel.svelte
<script>
  // Loads /benchmark-results.json written by demo/compare.py and renders a
  // side-by-side unidb vs Postgres comparison with bar charts.

  let data    = $state(null);
  let loading = $state(true);
  let error   = $state(null);

  async function loadResults() {
    loading = true;
    error   = null;
    try {
      const res = await fetch('/benchmark-results.json', { cache: 'no-store' });
      if (res.status === 404) {
        data = null;
      } else if (!res.ok) {
        error = `HTTP ${res.status}`;
      } else {
        data = await res.json();
      }
    } catch (e) {
      error = e.message;
    } finally {
      loading = false;
    }
  }

  $effect(() => { loadResults(); });

  // Max ms across all queries — used to normalize bar widths.
  const maxMs = $derived(() => {
    if (!data?.queries?.length) return 1;
    return Math.max(...data.queries.flatMap((q) => [q.unidb_ms ?? 0, q.postgres_ms ?? 0]));
  });

  function barPct(ms) {
    return Math.min(100, (ms / maxMs()) * 100);
  }

  function ratioLabel(r) {
    if (r == null) return '';
    if (r < 0.95)  return `unidb ${(1/r).toFixed(2)}× faster`;
    if (r > 1.05)  return `postgres ${r.toFixed(2)}× faster`;
    return 'roughly equal';
  }

  function ratioColor(r) {
    if (r == null) return 'var(--muted)';
    if (r < 0.8)  return '#22c55e';   // unidb clearly faster
    if (r < 0.95) return '#86efac';
    if (r > 1.25) return '#f87171';   // postgres clearly faster
    if (r > 1.05) return '#fca5a5';
    return 'var(--muted)';
  }

  function fmt(ms) {
    if (ms == null) return '—';
    return ms < 1000 ? `${ms.toFixed(1)} ms` : `${(ms/1000).toFixed(2)} s`;
  }

  function relTime(iso) {
    const diff = Date.now() - new Date(iso).getTime();
    if (diff < 60000)  return `${Math.floor(diff/1000)}s ago`;
    if (diff < 3600000) return `${Math.floor(diff/60000)}m ago`;
    return new Date(iso).toLocaleTimeString();
  }
</script>

<div class="compare">

  <!-- ── Header ──────────────────────────────────────────────────────────── -->
  <div class="topbar">
    <div class="topbar-left">
      <h2>unidb vs Postgres</h2>
      {#if data}
        <span class="badge">
          {data.size} · {data.n_cust?.toLocaleString()} customers ·
          {data.n_ord?.toLocaleString()} orders
        </span>
        <span class="run-time">run {relTime(data.run_at)}</span>
      {/if}
    </div>
    <button class="btn" onclick={loadResults}>↺ Refresh</button>
  </div>

  {#if loading}
    <p class="muted center">Loading…</p>

  {:else if error}
    <div class="notice err">Error loading results: {error}</div>

  {:else if !data}
    <div class="notice">
      <strong>No results yet.</strong> Run the comparison script to generate data:
      <pre>pip3 install psycopg2-binary
python3 demo/compare.py --size 10k</pre>
      Then click <em>Refresh</em> above.
    </div>

  {:else}

    <!-- ── Summary banner ─────────────────────────────────────────────── -->
    {#if data.summary}
      {@const s = data.summary}
      <div class="summary-row">
        <div class="summary-card unidb">
          <div class="eng-label">unidb</div>
          <div class="eng-total">{fmt(s.unidb_total_ms)}</div>
          <div class="eng-sub">total across {data.queries.length} queries</div>
        </div>
        <div class="vs">vs</div>
        <div class="summary-card pg">
          <div class="eng-label">PostgreSQL 16</div>
          <div class="eng-total">{fmt(s.postgres_total_ms)}</div>
          <div class="eng-sub">total across {data.queries.length} queries</div>
        </div>
        {#if s.ratio != null}
          <div class="verdict" style={`color:${ratioColor(s.ratio)}`}>
            {ratioLabel(s.ratio)}
            <div class="verdict-sub">overall</div>
          </div>
        {/if}
      </div>
    {/if}

    <!-- ── Per-query bars ──────────────────────────────────────────────── -->
    <div class="queries">
      {#each data.queries as q}
        <div class="query-row">
          <div class="q-label">{q.label}</div>
          <div class="bars">
            <!-- unidb bar -->
            <div class="bar-row">
              <span class="eng-tag unidb-tag">unidb</span>
              <div class="bar-track">
                <div class="bar unidb-bar" style={`width:${barPct(q.unidb_ms)}%`}></div>
              </div>
              <span class="bar-val">{fmt(q.unidb_ms)}</span>
            </div>
            <!-- postgres bar -->
            {#if q.postgres_ms != null}
              <div class="bar-row">
                <span class="eng-tag pg-tag">postgres</span>
                <div class="bar-track">
                  <div class="bar pg-bar" style={`width:${barPct(q.postgres_ms)}%`}></div>
                </div>
                <span class="bar-val">{fmt(q.postgres_ms)}</span>
              </div>
            {/if}
          </div>
          {#if q.ratio != null}
            <div class="q-ratio" style={`color:${ratioColor(q.ratio)}`}>
              {ratioLabel(q.ratio)}
            </div>
          {/if}
        </div>
      {/each}
    </div>

    <!-- ── Footer ─────────────────────────────────────────────────────── -->
    <div class="footer">
      unidb @ <code>{data.unidb_url}</code>
      {#if data.postgres_dsn}
        · postgres DSN: <code>{data.postgres_dsn}</code>
      {/if}
      <br>
      <span class="muted">
        Timings are browser/script round-trip (network included).
        Run <code>python3 demo/compare.py --size 50k</code> to refresh.
      </span>
    </div>
  {/if}
</div>

<style>
  .compare {
    display: flex;
    flex-direction: column;
    gap: 18px;
    font-size: 13px;
    max-width: 960px;
  }

  /* Top bar */
  .topbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .topbar-left {
    display: flex;
    align-items: baseline;
    gap: 10px;
    flex-wrap: wrap;
  }
  h2 { margin: 0; font-size: 15px; }
  .badge {
    background: var(--accent-faint, rgba(99,102,241,.1));
    color: var(--accent);
    border-radius: 10px;
    padding: 2px 8px;
    font-size: 11px;
    font-weight: 600;
  }
  .run-time { color: var(--muted); font-size: 11px; }
  .btn {
    background: var(--bg);
    border: 1px solid var(--border);
    border-radius: 5px;
    padding: 4px 12px;
    font-size: 12px;
    cursor: pointer;
    color: var(--muted);
  }
  .btn:hover { color: var(--text); }

  /* Summary banner */
  .summary-row {
    display: flex;
    align-items: center;
    gap: 18px;
    flex-wrap: wrap;
  }
  .summary-card {
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 14px 20px;
    min-width: 160px;
  }
  .summary-card.unidb { border-left: 4px solid var(--accent); }
  .summary-card.pg    { border-left: 4px solid #336791; }
  .eng-label { font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: var(--muted); }
  .eng-total { font-size: 26px; font-weight: 700; margin: 4px 0 2px; }
  .eng-sub   { font-size: 11px; color: var(--muted); }
  .vs { font-size: 18px; font-weight: 700; color: var(--muted); }
  .verdict { font-size: 14px; font-weight: 600; }
  .verdict-sub { font-size: 11px; color: var(--muted); font-weight: 400; margin-top: 2px; }

  /* Per-query rows */
  .queries { display: flex; flex-direction: column; gap: 14px; }
  .query-row {
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 12px 14px;
  }
  .q-label {
    font-weight: 600;
    margin-bottom: 8px;
  }
  .bars { display: flex; flex-direction: column; gap: 6px; }
  .bar-row {
    display: flex;
    align-items: center;
    gap: 8px;
  }
  .eng-tag {
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    width: 68px;
    flex-shrink: 0;
    letter-spacing: .04em;
  }
  .unidb-tag { color: var(--accent); }
  .pg-tag    { color: #336791; }
  .bar-track {
    flex: 1;
    background: var(--bg);
    border-radius: 3px;
    height: 12px;
    overflow: hidden;
  }
  .bar {
    height: 100%;
    border-radius: 3px;
    transition: width 0.4s ease;
  }
  .unidb-bar { background: var(--accent); opacity: 0.8; }
  .pg-bar    { background: #336791; opacity: 0.8; }
  .bar-val {
    font-variant-numeric: tabular-nums;
    font-size: 12px;
    width: 70px;
    text-align: right;
    flex-shrink: 0;
  }
  .q-ratio {
    margin-top: 6px;
    font-size: 11px;
    font-weight: 600;
  }

  /* Misc */
  .notice {
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 20px;
    background: var(--panel);
    line-height: 1.6;
  }
  .notice.err { border-color: #f87171; color: #ef4444; }
  .notice pre {
    background: var(--bg);
    padding: 10px;
    border-radius: 5px;
    font-size: 12px;
    margin: 10px 0 0;
  }
  .footer {
    font-size: 11px;
    color: var(--muted);
    line-height: 1.8;
    padding-top: 8px;
    border-top: 1px solid var(--border);
  }
  .footer code { font-family: var(--mono); }
  .muted { color: var(--muted); }
  .center { text-align: center; padding: 40px; }
</style>
