// src/components/ErrorBox.tsx
import type { CatalogError } from '@/hooks/useCatalog';

// Renders a normalized engine ApiError ({message, code, status}) verbatim —
// per DESIGN_SPEC §4 "Error display": never swallow or rewrite engine errors.
export function ErrorBox({ error }: { error: CatalogError | null | undefined }) {
  if (!error) return null;
  return (
    <div className="flex items-baseline gap-2.5 rounded-md border border-error/35 bg-error-subtle px-3 py-2 text-md" role="alert">
      <span className="font-mono font-semibold whitespace-nowrap text-error">
        {error.code}
        {error.status ? ` · ${error.status}` : ''}
      </span>
      <span className="text-foreground">{error.message}</span>
    </div>
  );
}

// src/lib/ErrorBox.svelte
<script>
  // Renders a normalized ApiError ({message, code, status}).
  let { error } = $props();
</script>

{#if error}
  <div class="err" role="alert">
    <span class="code">{error.code}{error.status ? ` · ${error.status}` : ''}</span>
    <span class="msg">{error.message}</span>
  </div>
{/if}

<style>
  .err {
    border: 1px solid var(--err-border);
    background: var(--err-bg);
    border-radius: 6px;
    padding: 8px 12px;
    display: flex;
    gap: 10px;
    align-items: baseline;
    font-size: 13px;
  }
  .code {
    font-family: var(--mono);
    font-weight: 600;
    color: var(--err-fg);
    white-space: nowrap;
  }
  .msg {
    color: var(--text);
  }
</style>
