// src/lib/ApiDocsPanel.svelte
<script>
  import { getRestOpenApi, restGet, BASE_URL } from './api.js';
  import ResultsGrid from './ResultsGrid.svelte';

  // API-docs panel (Workstream G4 — see ../../docs/AUTH_POLICY_PANELS_PLAN.md).
  // Live over engine item 123 (C1 resource routes + C3 OpenAPI doc, merged
  // via PR #223 on unidb main). Verified against src/server/rest_resource.rs
  // directly — docs/REST_API.md does not document /rest/v1 at all yet, even
  // though the route shipped (a real doc-staleness gap, not a Studio
  // workaround; flagged in the plan doc rather than guessed around).
  //
  // Two parts: (1) a schema + copy-paste curl viewer generated straight from
  // GET /rest/v1 (the engine's own OpenAPI doc — every value here is engine
  // data, never invented), and (2) a live GET explorer over
  // /rest/v1/<table> exercising the real select/filter/order/limit/offset
  // query surface, per the C1 operator allow-list
  // (eq/neq/gt/gte/lt/lte/like/ilike/in/is).

  let loading   = $state(true);
  let error     = $state(null);
  let supported = $state(true);
  let doc       = $state(null);

  let selectedTable = $state(null);

  const FILTER_OPS = ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'in', 'is'];

  $effect(() => { load(); });

  async function load() {
    loading = true;
    error = null;
    try {
      const out = await getRestOpenApi();
      supported = out.supported;
      doc = out.doc;
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
    } finally {
      loading = false;
    }
  }

  const tables = $derived.by(() => {
    if (!doc?.paths) return [];
    return Object.keys(doc.paths)
      .map((p) => p.replace(/^\/rest\/v1\//, ''))
      .sort();
  });

  function schemaFor(table) {
    return doc?.components?.schemas?.[table] ?? null;
  }
  function columnsFor(table) {
    const s = schemaFor(table);
    if (!s?.properties) return [];
    const required = new Set(s.required ?? []);
    // `x-primary-key` (table-level) is only populated from a table-level
    // `PRIMARY KEY (...)` constraint — verified against
    // src/server/rest_resource.rs::get_openapi on unidb main, it reads only
    // `def.constraints.primary_key`, not a column-level `PRIMARY KEY` marker
    // (e.g. `CREATE TABLE t (id BIGINT PRIMARY KEY, ...)`), so it misses that
    // common case. Each *column's* own `description: "primary key"` is set
    // from the column-level marker correctly, so union both signals rather
    // than trusting `x-primary-key` alone — otherwise a single-column PK
    // declared inline silently fails to highlight and the snippet builder
    // below picks the wrong "non-PK" example column.
    const pk = new Set(s['x-primary-key'] ?? []);
    return Object.entries(s.properties).map(([name, prop]) => ({
      name,
      type: prop.type ?? (prop.$ref ? 'object' : 'any'),
      format: prop.format ?? null,
      required: required.has(name),
      primaryKey: pk.has(name) || prop.description === 'primary key',
      description: prop.description ?? null,
    }));
  }

  function exampleValue(col) {
    if (col.type === 'integer') return 1;
    if (col.type === 'number') return 1.5;
    if (col.type === 'boolean') return true;
    if (col.type === 'array') return [];
    if (col.format === 'uuid') return '00000000-0000-0000-0000-000000000000';
    if (col.format === 'date-time') return '2026-01-01T00:00:00Z';
    if (col.format === 'date') return '2026-01-01';
    return 'example';
  }

  function selectTable(t) {
    selectedTable = t;
    resetExplorer();
  }

  // ── snippet builders ──────────────────────────────────────────────────────
  function snippetList(table) {
    return `curl -s "${BASE_URL}/rest/v1/${table}?limit=10" \\\n  -H "Authorization: Bearer $TOKEN"`;
  }
  function snippetFiltered(table) {
    const cols = columnsFor(table);
    const pk = cols.find((c) => c.primaryKey) ?? cols[0];
    if (!pk) return snippetList(table);
    return `curl -s "${BASE_URL}/rest/v1/${table}?${pk.name}=eq.${exampleValue(pk)}&select=${cols.map((c) => c.name).slice(0, 4).join(',')}" \\\n  -H "Authorization: Bearer $TOKEN"`;
  }
  function snippetInsert(table) {
    const cols = columnsFor(table).filter((c) => !c.primaryKey);
    const body = Object.fromEntries(cols.slice(0, 3).map((c) => [c.name, exampleValue(c)]));
    return `curl -s -X POST "${BASE_URL}/rest/v1/${table}" \\\n  -H "Authorization: Bearer $TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d '${JSON.stringify(body)}'`;
  }
  function snippetUpdate(table) {
    const cols = columnsFor(table);
    const pk = cols.find((c) => c.primaryKey) ?? cols[0];
    const target = cols.find((c) => !c.primaryKey) ?? cols[0];
    if (!pk || !target) return '';
    const body = { [target.name]: exampleValue(target) };
    return `curl -s -X PATCH "${BASE_URL}/rest/v1/${table}?${pk.name}=eq.${exampleValue(pk)}" \\\n  -H "Authorization: Bearer $TOKEN" \\\n  -H "Content-Type: application/json" \\\n  -d '${JSON.stringify(body)}'`;
  }
  function snippetDelete(table) {
    const cols = columnsFor(table);
    const pk = cols.find((c) => c.primaryKey) ?? cols[0];
    if (!pk) return '';
    return `curl -s -X DELETE "${BASE_URL}/rest/v1/${table}?${pk.name}=eq.${exampleValue(pk)}" \\\n  -H "Authorization: Bearer $TOKEN"`;
  }

  let copiedSnippet = $state(null);
  async function copySnippet(key, text) {
    try {
      await navigator.clipboard.writeText(text);
      copiedSnippet = key;
      setTimeout(() => { if (copiedSnippet === key) copiedSnippet = null; }, 1500);
    } catch { /* clipboard unavailable */ }
  }

  // ── GET explorer ───────────────────────────────────────────────────────────
  let explorerOpen = $state(false);
  let selectCols   = $state('');
  let filters      = $state([]); // [{column, op, value}]
  let orderRows    = $state([]); // [{column, desc}]
  let limit        = $state(50);
  let offset       = $state(0);
  let explorerBusy   = $state(false);
  let explorerError  = $state(null);
  let explorerResult = $state(null); // {type,columns,rows}
  let explorerUrl    = $state(null);
  let explorerMs      = $state(null);

  function resetExplorer() {
    explorerOpen = false;
    selectCols = '';
    filters = [];
    orderRows = [];
    limit = 50;
    offset = 0;
    explorerBusy = false;
    explorerError = null;
    explorerResult = null;
    explorerUrl = null;
    explorerMs = null;
  }

  function addFilter() {
    const cols = columnsFor(selectedTable);
    filters = [...filters, { column: cols[0]?.name ?? '', op: 'eq', value: '' }];
  }
  function removeFilter(i) {
    filters = filters.filter((_, idx) => idx !== i);
  }
  function onOpChange(i, op) {
    filters = filters.map((f, idx) => (idx === i ? { ...f, op, value: op === 'is' ? 'null' : '' } : f));
  }

  function addOrder() {
    const cols = columnsFor(selectedTable);
    orderRows = [...orderRows, { column: cols[0]?.name ?? '', desc: false }];
  }
  function removeOrder(i) {
    orderRows = orderRows.filter((_, idx) => idx !== i);
  }

  function opValueSegment(f) {
    if (f.op === 'in') return `(${f.value})`;
    return f.value;
  }

  async function runExplorer() {
    explorerBusy = true;
    explorerError = null;
    explorerResult = null;
    try {
      const filterParams = filters
        .filter((f) => f.column && f.op)
        .map((f) => [f.column, `${f.op}.${opValueSegment(f)}`]);
      const order = orderRows
        .filter((o) => o.column)
        .map((o) => `${o.column}.${o.desc ? 'desc' : 'asc'}`)
        .join(',');
      const out = await restGet(selectedTable, {
        select: selectCols.trim() || undefined,
        filterParams,
        order: order || undefined,
        limit,
        offset,
      });
      explorerResult = out.result;
      explorerUrl = out.url;
      explorerMs = out.roundTripMs;
    } catch (e) {
      explorerError = e.message ?? String(e);
    } finally {
      explorerBusy = false;
    }
  }
</script>

<div class="apidocs">
  {#if error}
    <div class="unsupported">
      <h3>Couldn't load the API docs</h3>
      <p class="err">{error.code}: {error.message}</p>
    </div>
  {:else if !loading && !supported}
    <div class="unsupported">
      <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
        <path d="M4 4h16v16H4z"/><path d="M8 9h8M8 13h5"/>
      </svg>
      <h3>API docs not available</h3>
      <p>This server doesn't expose <code>GET /rest/v1</code> yet (needs item-123 auto REST API support).</p>
    </div>
  {:else}
    <div class="layout">
      <!-- ── table sidebar ── -->
      <aside class="asidebar">
        <div class="sidebar-head">
          <span class="sidebar-title">Tables</span>
        </div>
        {#if loading}
          <p class="muted small">Loading…</p>
        {:else if tables.length === 0}
          <p class="muted small">No tables yet.</p>
        {:else}
          <ul class="entity-list">
            {#each tables as t}
              <li class:active={selectedTable === t}>
                <button class="entity-btn" onclick={() => selectTable(t)}>{t}</button>
              </li>
            {/each}
          </ul>
        {/if}
      </aside>

      <!-- ── detail ── -->
      <div class="detail">
        {#if !selectedTable}
          <div class="empty-state">
            <p>Select a table to see its schema, request snippets, and a live query explorer —
              all generated from <code>GET /rest/v1</code>, the engine's own OpenAPI document.</p>
          </div>
        {:else}
          {@const cols = columnsFor(selectedTable)}
          <h2 class="table-title">{selectedTable}</h2>

          <section class="block">
            <h4>Schema</h4>
            <table class="schema-table">
              <thead>
                <tr><th>Column</th><th>Type</th><th>Required</th><th></th></tr>
              </thead>
              <tbody>
                {#each cols as c}
                  <tr>
                    <td class="mono">{c.name}</td>
                    <td class="mono">{c.type}{c.format ? `(${c.format})` : ''}</td>
                    <td>{c.required ? 'yes' : 'no'}</td>
                    <td>
                      {#if c.primaryKey}<span class="pill pk">PK</span>{/if}
                      {#if c.description && !c.primaryKey}<span class="desc">{c.description}</span>{/if}
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </section>

          <section class="block">
            <h4>Request snippets</h4>
            <p class="hint">Set <code>$TOKEN</code> to a valid bearer token first — every
              <code>/rest/v1</code> route requires one, same as <code>/sql</code>.</p>
            {#each [
              ['List (first 10)', 'list', snippetList(selectedTable)],
              ['Filtered + column projection', 'filtered', snippetFiltered(selectedTable)],
              ['Insert', 'insert', snippetInsert(selectedTable)],
              ['Update (by primary key)', 'update', snippetUpdate(selectedTable)],
              ['Delete (by primary key)', 'delete', snippetDelete(selectedTable)],
            ] as [label, key, code]}
              {#if code}
                <div class="snippet">
                  <div class="snippet-head">
                    <span class="snippet-label">{label}</span>
                    <button class="copy-btn" onclick={() => copySnippet(key, code)}>
                      {copiedSnippet === key ? 'Copied' : 'Copy'}
                    </button>
                  </div>
                  <pre class="snippet-code">{code}</pre>
                </div>
              {/if}
            {/each}
          </section>

          <section class="block">
            <div class="explorer-head">
              <h4>Try it — GET explorer</h4>
              <button class="ghost" onclick={() => (explorerOpen = !explorerOpen)}>
                {explorerOpen ? 'Hide' : 'Open'}
              </button>
            </div>
            {#if explorerOpen}
              <div class="explorer">
                <label class="field">
                  <span class="flabel">select (comma-separated columns, blank = *)</span>
                  <input bind:value={selectCols} placeholder={cols.map((c) => c.name).join(',')} class="mono-input" />
                </label>

                <div class="field">
                  <span class="flabel">Filters</span>
                  {#each filters as f, i}
                    <div class="filter-row">
                      <select bind:value={f.column}>
                        {#each cols as c}<option value={c.name}>{c.name}</option>{/each}
                      </select>
                      <select value={f.op} onchange={(e) => onOpChange(i, e.target.value)}>
                        {#each FILTER_OPS as op}<option value={op}>{op}</option>{/each}
                      </select>
                      {#if f.op === 'is'}
                        <select bind:value={f.value}>
                          <option value="null">null</option>
                          <option value="true">true</option>
                          <option value="false">false</option>
                        </select>
                      {:else}
                        <input bind:value={f.value} placeholder={f.op === 'in' ? '1,2,3' : 'value'} class="mono-input" />
                      {/if}
                      <button class="del-btn" onclick={() => removeFilter(i)}>✕</button>
                    </div>
                  {/each}
                  <button class="ghost small-btn" onclick={addFilter}>+ Add filter</button>
                </div>

                <div class="field">
                  <span class="flabel">Order</span>
                  {#each orderRows as o, i}
                    <div class="filter-row">
                      <select bind:value={o.column}>
                        {#each cols as c}<option value={c.name}>{c.name}</option>{/each}
                      </select>
                      <select bind:value={o.desc}>
                        <option value={false}>asc</option>
                        <option value={true}>desc</option>
                      </select>
                      <button class="del-btn" onclick={() => removeOrder(i)}>✕</button>
                    </div>
                  {/each}
                  <button class="ghost small-btn" onclick={addOrder}>+ Add order</button>
                </div>

                <div class="limit-row">
                  <label class="field">
                    <span class="flabel">limit</span>
                    <input type="number" min="0" bind:value={limit} class="num-input" />
                  </label>
                  <label class="field">
                    <span class="flabel">offset</span>
                    <input type="number" min="0" bind:value={offset} class="num-input" />
                  </label>
                  <button onclick={runExplorer} disabled={explorerBusy}>{explorerBusy ? 'Running…' : 'Run'}</button>
                </div>

                {#if explorerUrl}<p class="explorer-url mono">{explorerUrl}{explorerMs != null ? ` · ${Math.round(explorerMs)} ms` : ''}</p>{/if}
                {#if explorerError}<p class="err">{explorerError}</p>{/if}
                {#if explorerResult}
                  <div class="explorer-result">
                    <ResultsGrid result={explorerResult} />
                  </div>
                {/if}
              </div>
            {/if}
          </section>
        {/if}
      </div>
    </div>
  {/if}
</div>

<style>
  .apidocs { display: flex; flex-direction: column; height: 100%; }

  .unsupported {
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    gap: 12px; height: 100%; color: var(--muted); text-align: center; padding: 40px;
  }
  .unsupported h3 { margin: 0; font-size: 16px; color: var(--text); }
  .unsupported p  { margin: 0; font-size: 13px; line-height: 1.6; }

  .layout { display: flex; height: 100%; min-height: 0; }

  .asidebar {
    width: 220px; flex-shrink: 0;
    border-right: 1px solid var(--border);
    display: flex; flex-direction: column;
    background: var(--panel-alt);
    overflow-y: auto;
  }
  .sidebar-head { padding: 10px 12px 8px; border-bottom: 1px solid var(--border); }
  .sidebar-title {
    font-size: 11px; font-weight: 700; text-transform: uppercase;
    letter-spacing: 0.07em; color: var(--muted);
  }
  .entity-list { list-style: none; margin: 0; padding: 4px 0; }
  .entity-list li { padding: 0 6px; border-radius: 6px; margin: 1px 4px; }
  .entity-list li.active { background: var(--accent); }
  .entity-list li.active .entity-btn { color: #fff; }
  .entity-btn {
    width: 100%; display: block; background: none; border: none; padding: 7px 4px; cursor: pointer;
    color: var(--text); font-size: 13px; text-align: left; font-family: var(--mono);
    overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  }

  .detail { flex: 1; min-width: 0; overflow-y: auto; padding: 16px 20px; display: flex; flex-direction: column; gap: 18px; }
  .empty-state {
    display: flex; align-items: center; justify-content: center;
    height: 100%; color: var(--muted); font-size: 13px; text-align: center; padding: 40px; max-width: 480px; margin: 0 auto;
  }
  .table-title { margin: 0; font-size: 18px; font-family: var(--mono); }

  .block h4 {
    margin: 0 0 8px; font-size: 12px; font-weight: 700; text-transform: uppercase;
    letter-spacing: 0.05em; color: var(--muted);
  }

  .schema-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .schema-table th, .schema-table td { padding: 6px 10px; border-bottom: 1px solid var(--border); text-align: left; }
  .schema-table th { font-size: 11px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: 0.04em; }
  .schema-table tr:last-child td { border-bottom: none; }
  .pill.pk {
    font-size: 9px; font-weight: 700; text-transform: uppercase; color: var(--accent);
    background: color-mix(in srgb, var(--accent) 12%, transparent); border-radius: 4px; padding: 1px 6px;
  }
  .desc { font-size: 11px; color: var(--muted); }

  .hint { font-size: 12px; color: var(--muted); margin: 0 0 10px; }
  .hint code { font-family: var(--mono); background: var(--panel-alt); border-radius: 4px; padding: 1px 4px; }

  .snippet { border: 1px solid var(--border); border-radius: 6px; margin-bottom: 8px; overflow: hidden; }
  .snippet-head {
    display: flex; align-items: center; justify-content: space-between;
    padding: 5px 10px; background: var(--panel-alt); border-bottom: 1px solid var(--border);
  }
  .snippet-label { font-size: 11px; font-weight: 600; color: var(--muted); }
  .copy-btn {
    background: none; border: 1px solid var(--border); border-radius: 5px;
    color: var(--muted); font-size: 11px; padding: 2px 8px; cursor: pointer;
  }
  .copy-btn:hover { color: var(--text); border-color: var(--accent); }
  .snippet-code {
    margin: 0; padding: 10px; font-family: var(--mono); font-size: 12px;
    white-space: pre-wrap; word-break: break-all; background: var(--panel);
  }

  .explorer-head { display: flex; align-items: center; justify-content: space-between; }
  .explorer-head h4 { margin: 0; }
  .explorer { display: flex; flex-direction: column; gap: 12px; margin-top: 10px; max-width: 700px; }
  .field { display: flex; flex-direction: column; gap: 4px; }
  .flabel { font-size: 12px; font-weight: 600; }
  .field input, .field select {
    padding: 6px 9px; font-size: 13px; color: var(--text); background: var(--panel);
    border: 1px solid var(--border); border-radius: 6px;
  }
  .mono-input { font-family: var(--mono); }
  .num-input { width: 90px; }
  .filter-row { display: flex; gap: 6px; align-items: center; margin-bottom: 4px; }
  .filter-row select, .filter-row input {
    padding: 5px 8px; font-size: 12px; color: var(--text); background: var(--panel);
    border: 1px solid var(--border); border-radius: 6px;
  }
  .limit-row { display: flex; gap: 12px; align-items: flex-end; }
  .del-btn { background: none; border: none; color: var(--muted); cursor: pointer; font-size: 12px; }
  .del-btn:hover { color: var(--err-fg); }
  .ghost {
    background: none; border: 1px solid var(--border); border-radius: 6px;
    color: var(--text); padding: 6px 12px; font-size: 13px; cursor: pointer; align-self: flex-start;
  }
  .small-btn { padding: 4px 10px; font-size: 12px; }
  .limit-row button:not(.ghost) {
    background: var(--accent); color: #fff; border: none;
    border-radius: 6px; padding: 7px 16px; font-size: 13px; cursor: pointer;
  }
  button:disabled { opacity: 0.5; cursor: default; }

  .explorer-url { font-size: 11px; color: var(--muted); word-break: break-all; margin: 0; }
  .explorer-result { border: 1px solid var(--border); border-radius: 6px; overflow: auto; max-height: 360px; }

  .muted { color: var(--muted); }
  .small { font-size: 12px; }
  .mono { font-family: var(--mono); }
  .err { color: var(--err-fg); }
</style>

// src/components/ApiDocsPanel.tsx
import { useEffect, useMemo, useState } from 'react';
import { FileCode, Play } from 'lucide-react';
import { getRestOpenApi, restRequest, BASE_URL } from '@/lib/engine/api.js';
import { DataGrid, type DataGridResult } from './DataGrid';
import { Textarea } from './ui/textarea';
import { ErrorBox } from './ErrorBox';
import { PanelHelp } from './PanelHelp';
import { cn } from '@/lib/utils';
import type { CatalogError } from '@/hooks/useCatalog';

// API-docs panel (item 123 C1/C3, C2 embedded resources, item 136 per-embed
// filter/order/limit/offset, item 139 Prefer/count) — built directly against
// GET /rest/v1's catalog-derived OpenAPI 3 doc + a live GET/POST/PATCH/DELETE
// explorer over /rest/v1/<table>. Every response reuses POST /sql's
// ExecResult shape, not a bare PostgREST array.

type Method = 'GET' | 'POST' | 'PATCH' | 'DELETE';
const METHODS: Method[] = ['GET', 'POST', 'PATCH', 'DELETE'];
const FILTER_OPS = ['eq', 'neq', 'gt', 'gte', 'lt', 'lte', 'like', 'ilike', 'in', 'is'] as const;

interface Filter {
  col: string;
  op: (typeof FILTER_OPS)[number];
  val: string;
}

function columnsFor(doc: any, table: string): { name: string; type: string; isPk: boolean }[] {
  const schema = doc?.components?.schemas?.[table];
  if (!schema?.properties) return [];
  const pkFromTableConstraint = new Set<string>(schema['x-primary-key'] ?? []);
  return Object.entries(schema.properties as Record<string, any>).map(([name, def]: [string, any]) => ({
    name,
    type: def.type ?? 'unknown',
    isPk: pkFromTableConstraint.has(name) || def.description === 'primary key',
  }));
}

export function ApiDocsPanel() {
  const [supported, setSupported] = useState(true);
  const [doc, setDoc] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<CatalogError | null>(null);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);

  useEffect(() => {
    getRestOpenApi()
      .then((out) => {
        setSupported(out.supported);
        setDoc(out.doc);
        const names = Object.keys(out.doc?.components?.schemas ?? {});
        if (names.length) setSelectedTable(names[0]);
      })
      .catch((e) => setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status }))
      .finally(() => setLoading(false));
  }, []);

  const tableNames = useMemo(() => (doc ? Object.keys(doc.components?.schemas ?? {}) : []), [doc]);
  const columns = useMemo(() => (selectedTable ? columnsFor(doc, selectedTable) : []), [doc, selectedTable]);

  // ---- explorer state ----
  const [method, setMethod] = useState<Method>('GET');
  const [selectCols, setSelectCols] = useState<Set<string>>(new Set());
  const [filters, setFilters] = useState<Filter[]>([]);
  const [orderCol, setOrderCol] = useState('');
  const [orderDir, setOrderDir] = useState<'asc' | 'desc'>('asc');
  const [limit, setLimit] = useState('50');
  const [offset, setOffset] = useState('0');
  const [extraParamsText, setExtraParamsText] = useState('');
  const [bodyText, setBodyText] = useState('{}');
  const [countExact, setCountExact] = useState(false);
  const [returnMode, setReturnMode] = useState<'' | 'representation' | 'minimal'>('');
  const [runBusy, setRunBusy] = useState(false);
  const [runError, setRunError] = useState<string | null>(null);
  const [runResult, setRunResult] = useState<any>(null);
  const [runMeta, setRunMeta] = useState<{ url: string; status: number; contentRange: string | null; preferenceApplied: string | null } | null>(null);

  useEffect(() => {
    setSelectCols(new Set());
    setFilters([]);
    setOrderCol('');
    setRunResult(null);
    setRunMeta(null);
    setRunError(null);
  }, [selectedTable]);

  function toggleSelectCol(c: string) {
    setSelectCols((s) => {
      const next = new Set(s);
      if (next.has(c)) next.delete(c);
      else next.add(c);
      return next;
    });
  }
  function addFilter() {
    setFilters((f) => [...f, { col: columns[0]?.name ?? '', op: 'eq', val: '' }]);
  }
  function updateFilter(i: number, patch: Partial<Filter>) {
    setFilters((f) => f.map((x, idx) => (idx === i ? { ...x, ...patch } : x)));
  }
  function removeFilter(i: number) {
    setFilters((f) => f.filter((_, idx) => idx !== i));
  }

  // Parse the free-text extra-params textarea (one `key=value` per line) into
  // [key, value] pairs — this is where item 136's dotted <embed>.<col>=<op>.<val>
  // / <embed>.order= / <embed>.limit= / <embed>.offset= params go, since their
  // key shape doesn't fit the fixed select/filter/order builder above.
  function parseExtraParams(): [string, string][] {
    return extraParamsText
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
      .map((l) => {
        const idx = l.indexOf('=');
        return idx === -1 ? [l, ''] : [l.slice(0, idx), l.slice(idx + 1)];
      });
  }

  async function runExplorer() {
    if (!selectedTable) return;
    setRunBusy(true);
    setRunError(null);
    setRunResult(null);
    setRunMeta(null);
    try {
      const opts: any = { countExact, return: returnMode || undefined };
      if (method === 'GET') {
        if (selectCols.size) opts.select = Array.from(selectCols).join(',');
        opts.filterParams = filters.filter((f) => f.col && f.val).map((f) => [f.col, `${f.op}.${f.val}`]);
        if (orderCol) opts.order = `${orderCol}.${orderDir}`;
        if (limit) opts.limit = Number(limit);
        if (offset) opts.offset = Number(offset);
        opts.extraParams = parseExtraParams();
      } else if (method === 'DELETE') {
        opts.filterParams = filters.filter((f) => f.col && f.val).map((f) => [f.col, `${f.op}.${f.val}`]);
      } else {
        opts.filterParams = filters.filter((f) => f.col && f.val).map((f) => [f.col, `${f.op}.${f.val}`]);
        try {
          opts.body = JSON.parse(bodyText);
        } catch {
          setRunError('Request body must be valid JSON.');
          setRunBusy(false);
          return;
        }
      }
      const out = await restRequest(selectedTable, method, opts);
      setRunResult(out.result);
      setRunMeta({ url: out.url, status: out.status, contentRange: out.contentRange, preferenceApplied: out.preferenceApplied });
    } catch (e: any) {
      setRunError(e?.message ?? String(e));
    } finally {
      setRunBusy(false);
    }
  }

  function curlSnippet(): string {
    if (!selectedTable) return '';
    const sel = selectCols.size ? `?select=${Array.from(selectCols).join(',')}` : '';
    return `curl -H "Authorization: Bearer $TOKEN" \\\n  "${BASE_URL}/rest/v1/${selectedTable}${sel}"`;
  }

  const inputCls =
    'h-8 rounded-md border border-border bg-secondary px-2 text-md outline-none focus-visible:border-border-strong focus-visible:ring-[2px] focus-visible:ring-ring/40';
  const btnCls = 'h-8 rounded-md bg-brand px-3 text-md font-semibold text-brand-text-on hover:bg-brand-hover disabled:opacity-45';
  const ghostBtnCls = 'h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong disabled:opacity-45';

  if (loading) return <p className="p-4 text-sm text-text-light">Loading…</p>;
  if (!supported) {
    return (
      <div className="flex flex-col gap-2 p-4">
        <h3 className="m-0 text-md font-semibold">API docs not available</h3>
        <p className="m-0 text-sm text-text-light">
          This server predates item 123 (<code>GET /rest/v1</code>).
        </p>
      </div>
    );
  }
  if (error) return <div className="p-4"><ErrorBox error={error} /></div>;

  return (
    <div className="flex h-full gap-4 p-4">
      <div className="flex w-56 shrink-0 flex-col gap-1 overflow-y-auto border-r border-border pr-3">
        <span className="mb-1 flex items-center gap-1.5 text-xs font-semibold tracking-wide text-text-muted uppercase">
          <FileCode className="size-3.5" /> Tables
        </span>
        {tableNames.map((t) => (
          <button
            key={t}
            onClick={() => setSelectedTable(t)}
            className={cn('rounded-md px-2 py-1.5 text-left font-mono text-md hover:bg-accent', selectedTable === t && 'bg-selected text-brand')}
          >
            {t}
          </button>
        ))}
      </div>

      <div className="flex flex-1 flex-col gap-3.5 overflow-y-auto">
        <PanelHelp
          summary="A live OpenAPI 3 view of the auto-generated REST API, plus a request explorer."
          what={
            <>
              Generated from the engine's own <code>GET /rest/v1</code> document — pick a table on the left to see its endpoints and copy curl
              snippets. The explorer runs real <code>GET/POST/PATCH/DELETE</code> against <code>/rest/v1/&lt;table&gt;</code> with{' '}
              <code>select=</code> + embedded FK expansion, filter operators
              (<code>eq/neq/gt/gte/lt/lte/like/ilike/in/is</code>), <code>order=</code>/<code>limit</code>/<code>offset</code>, and{' '}
              <code>Prefer: count=exact</code> / <code>return=representation</code> (real <code>Content-Range</code> headers shown). Same
              RLS/grant enforcement as <code>/sql</code>.
            </>
          }
          actions={[
            'Pick a table, then run a GET with a filter like status=eq.paid&limit=5',
            'Add Prefer: count=exact and read the Content-Range response header',
          ]}
          routes={['GET /rest/v1', 'GET/POST/PATCH/DELETE /rest/v1/{table}']}
        />
        {selectedTable && (
          <>
            <div>
              <h3 className="m-0 mb-1 font-mono text-md font-semibold">{selectedTable}</h3>
              <div className="flex flex-wrap gap-1">
                {columns.map((c) => (
                  <span key={c.name} className={cn('rounded-sm border border-border bg-secondary px-1.5 py-0.5 font-mono text-xs', c.isPk && 'border-brand text-brand')}>
                    {c.name}: {c.type}
                    {c.isPk ? ' (PK)' : ''}
                  </span>
                ))}
              </div>
            </div>

            <div className="rounded-md border border-border bg-secondary/40 p-2">
              <pre className="m-0 overflow-x-auto font-mono text-xs whitespace-pre-wrap text-text-light">{curlSnippet()}</pre>
            </div>

            <div className="flex gap-1">
              {METHODS.map((m) => (
                <button
                  key={m}
                  onClick={() => setMethod(m)}
                  className={cn('rounded-md border border-border px-3 py-1 text-sm font-semibold', method === m ? 'bg-brand text-brand-text-on' : 'bg-secondary hover:border-border-strong')}
                >
                  {m}
                </button>
              ))}
            </div>

            {method === 'GET' && (
              <>
                <div className="flex flex-col gap-1">
                  <span className="text-xs font-semibold tracking-wide text-text-muted uppercase">select=</span>
                  <div className="flex flex-wrap gap-2">
                    {columns.map((c) => (
                      <label key={c.name} className="flex items-center gap-1 text-sm">
                        <input type="checkbox" checked={selectCols.has(c.name)} onChange={() => toggleSelectCol(c.name)} /> {c.name}
                      </label>
                    ))}
                  </div>
                </div>
                <div className="flex items-end gap-2">
                  <label className="flex flex-col gap-1 text-sm text-text-light">
                    order
                    <select value={orderCol} onChange={(e) => setOrderCol(e.target.value)} className={inputCls}>
                      <option value="">(none)</option>
                      {columns.map((c) => (
                        <option key={c.name} value={c.name}>
                          {c.name}
                        </option>
                      ))}
                    </select>
                  </label>
                  <select value={orderDir} onChange={(e) => setOrderDir(e.target.value as any)} className={inputCls}>
                    <option value="asc">asc</option>
                    <option value="desc">desc</option>
                  </select>
                  <label className="flex flex-col gap-1 text-sm text-text-light">
                    limit
                    <input value={limit} onChange={(e) => setLimit(e.target.value)} className={cn(inputCls, 'w-20')} />
                  </label>
                  <label className="flex flex-col gap-1 text-sm text-text-light">
                    offset
                    <input value={offset} onChange={(e) => setOffset(e.target.value)} className={cn(inputCls, 'w-20')} />
                  </label>
                  <label className="flex items-center gap-1.5 text-md">
                    <input type="checkbox" checked={countExact} onChange={(e) => setCountExact(e.target.checked)} /> Prefer: count=exact
                  </label>
                </div>
              </>
            )}

            {method !== 'GET' && (
              <label className="flex items-center gap-1.5 text-md">
                <span className="text-sm text-text-light">Prefer: return=</span>
                <select value={returnMode} onChange={(e) => setReturnMode(e.target.value as any)} className={inputCls}>
                  <option value="">(default)</option>
                  <option value="representation">representation</option>
                  <option value="minimal">minimal</option>
                </select>
              </label>
            )}

            {method !== 'POST' && (
              <div className="flex flex-col gap-1">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-semibold tracking-wide text-text-muted uppercase">filters {method !== 'GET' ? '(row target)' : ''}</span>
                  <button className={cn(ghostBtnCls, 'h-6 px-2 text-xs')} onClick={addFilter}>
                    + filter
                  </button>
                </div>
                {filters.map((f, i) => (
                  <div key={i} className="flex gap-2">
                    <select value={f.col} onChange={(e) => updateFilter(i, { col: e.target.value })} className={inputCls}>
                      {columns.map((c) => (
                        <option key={c.name} value={c.name}>
                          {c.name}
                        </option>
                      ))}
                    </select>
                    <select value={f.op} onChange={(e) => updateFilter(i, { op: e.target.value as any })} className={inputCls}>
                      {FILTER_OPS.map((op) => (
                        <option key={op} value={op}>
                          {op}
                        </option>
                      ))}
                    </select>
                    <input value={f.val} onChange={(e) => updateFilter(i, { val: e.target.value })} className={cn(inputCls, 'flex-1')} spellCheck={false} />
                    <button className="text-sm text-text-muted hover:text-error" onClick={() => removeFilter(i)}>
                      ✕
                    </button>
                  </div>
                ))}
              </div>
            )}

            {(method === 'POST' || method === 'PATCH') && (
              <label className="flex flex-col gap-1 text-sm text-text-light">
                JSON body
                <Textarea value={bodyText} onChange={(e) => setBodyText(e.target.value)} spellCheck={false} className="min-h-20 font-mono" />
              </label>
            )}

            {method === 'GET' && (
              <label className="flex flex-col gap-1 text-sm text-text-light">
                Embedded resources / raw extra params (item 136 — one <code>key=value</code> per line, e.g.{' '}
                <code>select=id,orders()</code> + <code>orders.customer_id=eq.1</code> + <code>orders.order=id.desc</code>)
                <Textarea value={extraParamsText} onChange={(e) => setExtraParamsText(e.target.value)} spellCheck={false} className="min-h-14 font-mono text-sm" />
              </label>
            )}

            <div>
              <button className={cn(btnCls, 'flex items-center gap-1.5')} onClick={runExplorer} disabled={runBusy}>
                <Play className="size-3.5" /> {runBusy ? 'Running…' : 'Run'}
              </button>
            </div>

            {runError && <p className="m-0 text-sm text-error">{runError}</p>}

            {runMeta && (
              <div className="flex flex-wrap items-center gap-3 rounded-md border border-border bg-secondary/40 px-3 py-1.5 font-mono text-xs text-text-light">
                <span>{runMeta.status}</span>
                <span className="truncate">{runMeta.url}</span>
                {runMeta.contentRange && <span>Content-Range: {runMeta.contentRange}</span>}
                {runMeta.preferenceApplied && <span>Preference-Applied: {runMeta.preferenceApplied}</span>}
              </div>
            )}

            {runResult != null &&
              (runResult?.type === 'rows' ? (
                <DataGrid result={runResult as DataGridResult} />
              ) : (
                <pre className="m-0 rounded-md border border-border bg-secondary px-3 py-2 font-mono text-sm">{JSON.stringify(runResult, null, 2)}</pre>
              ))}
            {runResult == null && runMeta && <p className="m-0 text-sm text-text-light">(empty body — return=minimal or a plain DELETE)</p>}
          </>
        )}
      </div>
    </div>
  );
}
