// src/lib/StoragePanel.svelte
<script>
  import {
    listBuckets, createBucket, deleteBucket,
    listObjects, uploadObject, deleteObject, getObjectUrl,
  } from './api.js';

  // ── state ────────────────────────────────────────────────────
  let supported     = $state(true);
  let buckets       = $state([]);
  let bucketsLoading = $state(true);
  let bucketsError  = $state(null);

  let selectedBucket = $state(null);
  let prefix         = $state('');       // current folder path
  let objects        = $state([]);       // { key, size, last_modified, content_type }
  let folders        = $state([]);       // common prefixes (virtual folders)
  let objLoading     = $state(false);
  let objError       = $state(null);

  // new-bucket modal
  let newBucketOpen   = $state(false);
  let newBucketName   = $state('');
  let newBucketPublic = $state(false);
  let newBucketBusy   = $state(false);
  let newBucketError  = $state(null);

  // delete-bucket confirm
  let deleteBucketTarget = $state(null);
  let deleteBucketBusy   = $state(false);

  // upload
  let uploading    = $state(false);
  let uploadPct    = $state(0);
  let uploadError  = $state(null);
  let fileInputEl  = $state(null);
  let dragOver     = $state(false);

  // delete-object confirm
  let deleteObjTarget = $state(null);
  let deleteObjBusy   = $state(false);

  // copy URL feedback
  let copiedKey = $state(null);

  // ── lifecycle ────────────────────────────────────────────────
  $effect(() => { loadBuckets(); });

  $effect(() => {
    if (selectedBucket) loadObjects(selectedBucket, prefix);
  });

  async function loadBuckets() {
    bucketsLoading = true;
    bucketsError = null;
    try {
      const out = await listBuckets();
      supported = out.supported;
      buckets = out.buckets;
    } catch (e) {
      bucketsError = e.message;
    } finally {
      bucketsLoading = false;
    }
  }

  async function loadObjects(bucket, pfx) {
    objLoading = true;
    objError = null;
    try {
      const out = await listObjects(bucket, pfx);
      folders = (out.prefixes ?? []).map(p => ({ key: p, name: p.slice(pfx.length).replace(/\/$/, '') }));
      objects = (out.objects ?? []).filter(o => o.key !== pfx); // exclude the "folder" object itself
    } catch (e) {
      objError = e.message;
      folders = [];
      objects = [];
    } finally {
      objLoading = false;
    }
  }

  function selectBucket(b) {
    selectedBucket = b;
    prefix = '';
  }

  function openFolder(folderPrefix) {
    prefix = folderPrefix;
    loadObjects(selectedBucket, prefix);
  }

  function navigateCrumb(idx) {
    const parts = prefix.split('/').filter(Boolean);
    prefix = parts.slice(0, idx + 1).join('/') + (idx >= 0 ? '/' : '');
    loadObjects(selectedBucket, prefix);
  }

  // breadcrumb parts from prefix
  const crumbs = $derived(() => {
    const parts = prefix.split('/').filter(Boolean);
    return parts.map((p, i) => ({ label: p, index: i }));
  });

  // ── bucket CRUD ──────────────────────────────────────────────
  async function submitNewBucket() {
    newBucketError = null;
    const n = newBucketName.trim();
    if (!n) { newBucketError = 'Bucket name is required'; return; }
    newBucketBusy = true;
    try {
      await createBucket(n, { isPublic: newBucketPublic });
      newBucketOpen = false;
      newBucketName = '';
      newBucketPublic = false;
      await loadBuckets();
    } catch (e) {
      newBucketError = e.message;
    } finally {
      newBucketBusy = false;
    }
  }

  async function confirmDeleteBucket() {
    deleteBucketBusy = true;
    try {
      await deleteBucket(deleteBucketTarget);
      if (selectedBucket === deleteBucketTarget) { selectedBucket = null; prefix = ''; }
      deleteBucketTarget = null;
      await loadBuckets();
    } catch (e) {
      bucketsError = e.message;
    } finally {
      deleteBucketBusy = false;
    }
  }

  // ── upload ───────────────────────────────────────────────────
  function pickFiles() { fileInputEl?.click(); }

  async function handleFiles(files) {
    if (!files?.length || !selectedBucket) return;
    uploading = true;
    uploadError = null;
    try {
      for (const file of files) {
        uploadPct = 0;
        const key = prefix + file.name;
        await uploadObject(selectedBucket, key, file, (p) => { uploadPct = p; });
      }
      await loadObjects(selectedBucket, prefix);
    } catch (e) {
      uploadError = e.message;
    } finally {
      uploading = false;
      uploadPct = 0;
    }
  }

  function onFileInput(e) { handleFiles(e.target.files); e.target.value = ''; }

  function onDrop(e) {
    e.preventDefault();
    dragOver = false;
    handleFiles(e.dataTransfer.files);
  }

  // ── delete object ─────────────────────────────────────────────
  async function confirmDeleteObj() {
    deleteObjBusy = true;
    try {
      await deleteObject(selectedBucket, deleteObjTarget);
      deleteObjTarget = null;
      await loadObjects(selectedBucket, prefix);
    } catch (e) {
      objError = e.message;
    } finally {
      deleteObjBusy = false;
    }
  }

  // ── presigned URL ─────────────────────────────────────────────
  async function copyUrl(key) {
    try {
      const url = await getObjectUrl(selectedBucket, key);
      await navigator.clipboard.writeText(url);
      copiedKey = key;
      setTimeout(() => { if (copiedKey === key) copiedKey = null; }, 2000);
    } catch (e) {
      objError = e.message;
    }
  }

  async function downloadObj(key) {
    try {
      const url = await getObjectUrl(selectedBucket, key);
      const a = document.createElement('a');
      a.href = url;
      a.download = key.split('/').pop();
      a.click();
    } catch (e) {
      objError = e.message;
    }
  }

  // ── formatting ────────────────────────────────────────────────
  function fmtSize(bytes) {
    if (bytes == null) return '—';
    if (bytes >= 1_073_741_824) return `${(bytes / 1_073_741_824).toFixed(1)} GB`;
    if (bytes >= 1_048_576)     return `${(bytes / 1_048_576).toFixed(1)} MB`;
    if (bytes >= 1_024)         return `${(bytes / 1_024).toFixed(1)} KB`;
    return `${bytes} B`;
  }

  function fmtDate(iso) {
    if (!iso) return '—';
    const d = new Date(iso);
    const diff = Date.now() - d.getTime();
    if (diff < 60_000)        return 'just now';
    if (diff < 3_600_000)     return `${Math.floor(diff / 60_000)}m ago`;
    if (diff < 86_400_000)    return `${Math.floor(diff / 3_600_000)}h ago`;
    if (diff < 7 * 86_400_000) return `${Math.floor(diff / 86_400_000)}d ago`;
    return d.toLocaleDateString();
  }

  function fileIcon(key, contentType) {
    const ext = key.split('.').pop()?.toLowerCase();
    if (['jpg','jpeg','png','gif','webp','svg','avif'].includes(ext)) return '🖼';
    if (['mp4','mov','avi','mkv','webm'].includes(ext)) return '🎬';
    if (['mp3','wav','ogg','flac'].includes(ext)) return '🎵';
    if (['pdf'].includes(ext)) return '📄';
    if (['zip','tar','gz','bz2','7z'].includes(ext)) return '🗜';
    if (['json','yaml','yml','toml','xml'].includes(ext)) return '📋';
    if (['js','ts','py','rs','go','java','cpp','c','sql'].includes(ext)) return '📝';
    return '📄';
  }
</script>

<div class="storage">
  {#if !supported}
    <div class="unsupported">
      <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5">
        <ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v5c0 1.66 4.03 3 9 3s9-1.34 9-3V5"/>
        <path d="M3 10v5c0 1.66 4.03 3 9 3s9-1.34 9-3v-5"/>
      </svg>
      <h3>Storage not available</h3>
      <p>The unidb engine doesn't expose <code>GET /storage/buckets</code> yet.<br/>
         Wire up the MinIO proxy in the engine to enable object storage.</p>
    </div>
  {:else}
    <div class="layout">
      <!-- ── Bucket sidebar ── -->
      <aside class="bucket-sidebar">
        <div class="sidebar-head">
          <span class="sidebar-title">Buckets</span>
          <button class="icon-btn" title="New bucket" onclick={() => (newBucketOpen = true)}>+</button>
          <button class="icon-btn" title="Refresh" onclick={loadBuckets}>↻</button>
        </div>

        {#if bucketsError}
          <p class="err small">{bucketsError}</p>
        {:else if bucketsLoading}
          <p class="muted small">Loading…</p>
        {:else if buckets.length === 0}
          <p class="muted small">No buckets yet.</p>
        {:else}
          <ul class="bucket-list">
            {#each buckets as b}
              {@const name = b.name ?? b}
              <li class:active={selectedBucket === name}>
                <button class="bucket-btn" onclick={() => selectBucket(name)}>
                  <svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" style="flex-shrink:0">
                    <ellipse cx="8" cy="4" rx="6" ry="2"/><path d="M2 4v5c0 1.1 2.69 2 6 2s6-.9 6-2V4"/>
                    <path d="M2 9v3c0 1.1 2.69 2 6 2s6-.9 6-2V9"/>
                  </svg>
                  <span class="bucket-name">{name}</span>
                  {#if b.public}<span class="pub-badge">public</span>{/if}
                </button>
                <button class="del-bucket-btn" title="Delete bucket" onclick={(e) => { e.stopPropagation(); deleteBucketTarget = name; }}>✕</button>
              </li>
            {/each}
          </ul>
        {/if}
      </aside>

      <!-- ── Object browser ── -->
      <div class="browser">
        {#if !selectedBucket}
          <div class="empty-state">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.2">
              <ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M3 5v5c0 1.66 4.03 3 9 3s9-1.34 9-3V5"/>
              <path d="M3 10v5c0 1.66 4.03 3 9 3s9-1.34 9-3v-5"/>
            </svg>
            <p>Select a bucket to browse objects</p>
          </div>
        {:else}
          <!-- toolbar -->
          <div class="browser-toolbar">
            <!-- breadcrumb -->
            <nav class="crumb">
              <button class="crumb-item" onclick={() => { prefix = ''; loadObjects(selectedBucket, ''); }}>
                {selectedBucket}
              </button>
              {#each crumbs() as c}
                <span class="crumb-sep">/</span>
                <button class="crumb-item" onclick={() => navigateCrumb(c.index)}>{c.label}</button>
              {/each}
            </nav>
            <span class="grow"></span>
            <!-- upload -->
            <input bind:this={fileInputEl} type="file" multiple style="display:none" onchange={onFileInput} />
            <button class="upload-btn" onclick={pickFiles} disabled={uploading}>
              {#if uploading}
                <span class="spinner"></span> {Math.round(uploadPct * 100)}%
              {:else}
                ↑ Upload
              {/if}
            </button>
            <button class="refresh-btn" onclick={() => loadObjects(selectedBucket, prefix)} disabled={objLoading}>↻</button>
          </div>

          {#if uploadError}<p class="err small">{uploadError}</p>{/if}
          {#if objError}<p class="err small">{objError}</p>{/if}

          <!-- drop zone + table -->
          <div
            class="drop-zone"
            class:drag-over={dragOver}
            ondragover={(e) => { e.preventDefault(); dragOver = true; }}
            ondragleave={() => (dragOver = false)}
            ondrop={onDrop}
            role="region"
            aria-label="Drop files to upload"
          >
            {#if objLoading}
              <p class="muted center">Loading…</p>
            {:else if folders.length === 0 && objects.length === 0}
              <div class="empty-state small">
                <p>This {prefix ? 'folder' : 'bucket'} is empty.<br/>
                   <span class="muted">Drag files here or click Upload.</span></p>
              </div>
            {:else}
              <table class="obj-table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th class="num">Size</th>
                    <th>Modified</th>
                    <th>Type</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  <!-- folders first -->
                  {#each folders as f}
                    <tr class="folder-row" ondblclick={() => openFolder(f.key)}>
                      <td class="name-cell">
                        <button class="folder-btn" onclick={() => openFolder(f.key)}>
                          <span class="file-icon">📁</span>
                          {f.name}/
                        </button>
                      </td>
                      <td class="num muted">—</td>
                      <td class="muted">—</td>
                      <td class="muted">folder</td>
                      <td></td>
                    </tr>
                  {/each}
                  <!-- objects -->
                  {#each objects as o}
                    {@const shortName = o.key.slice(prefix.length)}
                    <tr>
                      <td class="name-cell">
                        <span class="file-icon">{fileIcon(o.key, o.content_type)}</span>
                        <span class="file-name" title={o.key}>{shortName}</span>
                      </td>
                      <td class="num mono">{fmtSize(o.size)}</td>
                      <td class="muted">{fmtDate(o.last_modified)}</td>
                      <td class="muted type-cell" title={o.content_type}>{o.content_type?.split('/')[1] ?? '—'}</td>
                      <td class="actions-cell">
                        <button class="action-btn" title="Download" onclick={() => downloadObj(o.key)}>↓</button>
                        <button
                          class="action-btn"
                          title={copiedKey === o.key ? 'Copied!' : 'Copy URL'}
                          onclick={() => copyUrl(o.key)}
                        >{copiedKey === o.key ? '✓' : '🔗'}</button>
                        <button class="action-btn danger" title="Delete" onclick={() => (deleteObjTarget = o.key)}>✕</button>
                      </td>
                    </tr>
                  {/each}
                </tbody>
              </table>
            {/if}

            {#if dragOver}
              <div class="drop-overlay">Drop to upload</div>
            {/if}
          </div>
        {/if}
      </div>
    </div>
  {/if}
</div>

<!-- ── New bucket modal ── -->
{#if newBucketOpen}
  <div class="modal-backdrop" role="presentation" onpointerdown={() => (newBucketOpen = false)}>
    <div class="modal" role="dialog" aria-label="New bucket" onpointerdown={(e) => e.stopPropagation()}>
      <div class="modal-head">
        <strong>New bucket</strong>
        <button class="x" onclick={() => (newBucketOpen = false)}>✕</button>
      </div>
      <div class="modal-body">
        <label class="field">
          <span class="flabel">Bucket name</span>
          <input bind:value={newBucketName} placeholder="e.g. my-assets" spellcheck="false"
                 onkeydown={(e) => e.key === 'Enter' && submitNewBucket()} />
        </label>
        <label class="check-field">
          <input type="checkbox" bind:checked={newBucketPublic} />
          Public bucket (objects accessible without auth)
        </label>
        {#if newBucketError}<p class="err">{newBucketError}</p>{/if}
      </div>
      <div class="modal-foot">
        <span class="grow"></span>
        <button class="ghost" onclick={() => (newBucketOpen = false)}>Cancel</button>
        <button onclick={submitNewBucket} disabled={newBucketBusy}>
          {newBucketBusy ? 'Creating…' : 'Create bucket'}
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- ── Delete bucket confirm ── -->
{#if deleteBucketTarget}
  <div class="modal-backdrop" role="presentation" onpointerdown={() => (deleteBucketTarget = null)}>
    <div class="modal del-modal" role="dialog" onpointerdown={(e) => e.stopPropagation()}>
      <div class="modal-head">
        <strong>Delete bucket</strong>
        <button class="x" onclick={() => (deleteBucketTarget = null)}>✕</button>
      </div>
      <div class="modal-body">
        <p class="del-msg">
          Permanently delete bucket <code>{deleteBucketTarget}</code> and <strong>all its objects</strong>?
          This cannot be undone.
        </p>
      </div>
      <div class="modal-foot">
        <span class="grow"></span>
        <button class="ghost" onclick={() => (deleteBucketTarget = null)}>Cancel</button>
        <button class="del-btn" onclick={confirmDeleteBucket} disabled={deleteBucketBusy}>
          {deleteBucketBusy ? 'Deleting…' : 'Delete bucket'}
        </button>
      </div>
    </div>
  </div>
{/if}

<!-- ── Delete object confirm ── -->
{#if deleteObjTarget}
  <div class="modal-backdrop" role="presentation" onpointerdown={() => (deleteObjTarget = null)}>
    <div class="modal del-modal" role="dialog" onpointerdown={(e) => e.stopPropagation()}>
      <div class="modal-head">
        <strong>Delete object</strong>
        <button class="x" onclick={() => (deleteObjTarget = null)}>✕</button>
      </div>
      <div class="modal-body">
        <p class="del-msg">Permanently delete <code>{deleteObjTarget.split('/').pop()}</code>?</p>
      </div>
      <div class="modal-foot">
        <span class="grow"></span>
        <button class="ghost" onclick={() => (deleteObjTarget = null)}>Cancel</button>
        <button class="del-btn" onclick={confirmDeleteObj} disabled={deleteObjBusy}>
          {deleteObjBusy ? 'Deleting…' : 'Delete'}
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .storage { display: flex; flex-direction: column; height: 100%; }

  /* ── unsupported ── */
  .unsupported {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
    height: 100%;
    color: var(--muted);
    text-align: center;
  }
  .unsupported h3 { margin: 0; font-size: 16px; color: var(--text); }
  .unsupported p  { margin: 0; font-size: 13px; line-height: 1.6; }

  /* ── layout ── */
  .layout {
    display: flex;
    height: 100%;
    min-height: 0;
    gap: 0;
  }

  /* ── bucket sidebar ── */
  .bucket-sidebar {
    width: 220px;
    flex-shrink: 0;
    border-right: 1px solid var(--border);
    display: flex;
    flex-direction: column;
    background: var(--panel-alt);
    overflow: hidden;
  }
  .sidebar-head {
    display: flex;
    align-items: center;
    gap: 4px;
    padding: 10px 12px 8px;
    border-bottom: 1px solid var(--border);
  }
  .sidebar-title {
    font-size: 11px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.07em;
    color: var(--muted);
    flex: 1;
  }
  .icon-btn {
    background: none;
    border: 1px solid var(--border);
    border-radius: 4px;
    color: var(--muted);
    font-size: 14px;
    width: 22px;
    height: 22px;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    padding: 0;
  }
  .icon-btn:hover { color: var(--text); border-color: var(--accent); }

  .bucket-list {
    list-style: none;
    margin: 0;
    padding: 6px 0;
    overflow-y: auto;
    flex: 1;
  }
  .bucket-list li {
    display: flex;
    align-items: center;
    padding: 0 6px;
    border-radius: 6px;
    margin: 1px 4px;
  }
  .bucket-list li.active { background: var(--accent); }
  .bucket-list li.active .bucket-btn { color: #fff; }
  .bucket-list li.active .del-bucket-btn { color: rgba(255,255,255,0.6); }
  .bucket-btn {
    flex: 1;
    display: flex;
    align-items: center;
    gap: 6px;
    background: none;
    border: none;
    padding: 7px 4px;
    cursor: pointer;
    color: var(--text);
    font-size: 13px;
    text-align: left;
    min-width: 0;
  }
  .bucket-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .pub-badge {
    font-size: 9px;
    font-weight: 700;
    text-transform: uppercase;
    background: rgba(37,99,235,0.15);
    color: var(--accent);
    border-radius: 3px;
    padding: 1px 4px;
    flex-shrink: 0;
  }
  .del-bucket-btn {
    background: none;
    border: none;
    color: var(--muted);
    cursor: pointer;
    font-size: 12px;
    padding: 2px 4px;
    opacity: 0;
    flex-shrink: 0;
  }
  .bucket-list li:hover .del-bucket-btn,
  .bucket-list li.active .del-bucket-btn { opacity: 1; }
  .del-bucket-btn:hover { color: var(--err-fg); }

  /* ── browser ── */
  .browser {
    flex: 1;
    display: flex;
    flex-direction: column;
    min-width: 0;
    overflow: hidden;
  }
  .browser-toolbar {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 10px 16px;
    border-bottom: 1px solid var(--border);
    flex-shrink: 0;
  }
  .crumb {
    display: flex;
    align-items: center;
    gap: 2px;
    font-size: 13px;
    flex: 1;
    min-width: 0;
    overflow: hidden;
  }
  .crumb-item {
    background: none;
    border: none;
    color: var(--accent);
    cursor: pointer;
    font-size: 13px;
    font-weight: 600;
    padding: 2px 4px;
    border-radius: 4px;
    white-space: nowrap;
  }
  .crumb-item:hover { background: var(--panel-alt); }
  .crumb-sep { color: var(--muted); padding: 0 2px; }
  .grow { flex: 1; }
  .upload-btn {
    background: var(--accent);
    color: #fff;
    border: none;
    border-radius: 6px;
    padding: 6px 14px;
    font-size: 13px;
    font-weight: 500;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 6px;
    white-space: nowrap;
  }
  .upload-btn:disabled { opacity: 0.6; cursor: default; }
  .refresh-btn {
    background: none;
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--muted);
    font-size: 14px;
    padding: 5px 9px;
    cursor: pointer;
  }
  .refresh-btn:hover { color: var(--text); border-color: var(--accent); }

  /* ── drop zone ── */
  .drop-zone {
    flex: 1;
    overflow: auto;
    position: relative;
  }
  .drop-zone.drag-over::after {
    content: '';
    position: absolute;
    inset: 0;
    background: rgba(37,99,235,0.06);
    border: 2px dashed var(--accent);
    border-radius: 8px;
    pointer-events: none;
  }
  .drop-overlay {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 18px;
    font-weight: 600;
    color: var(--accent);
    pointer-events: none;
  }

  /* ── object table ── */
  .obj-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 13px;
  }
  .obj-table th {
    position: sticky;
    top: 0;
    background: var(--panel);
    text-align: left;
    padding: 8px 12px;
    font-size: 11px;
    font-weight: 600;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    border-bottom: 1px solid var(--border);
    z-index: 1;
  }
  .obj-table th.num, .obj-table td.num { text-align: right; }
  .obj-table td {
    padding: 8px 12px;
    border-bottom: 1px solid var(--border);
    vertical-align: middle;
  }
  .obj-table tr:hover td { background: var(--panel-alt); }
  .obj-table tr:last-child td { border-bottom: none; }

  .name-cell { display: flex; align-items: center; gap: 8px; max-width: 400px; }
  .file-icon { font-size: 14px; flex-shrink: 0; }
  .file-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .folder-btn {
    background: none; border: none; cursor: pointer; color: var(--accent);
    font-size: 13px; font-weight: 500; display: flex; align-items: center; gap: 8px; padding: 0;
  }
  .folder-btn:hover { text-decoration: underline; }
  .type-cell { font-size: 11px; max-width: 100px; overflow: hidden; text-overflow: ellipsis; }

  .actions-cell {
    display: flex;
    align-items: center;
    gap: 4px;
    white-space: nowrap;
  }
  .action-btn {
    background: none;
    border: 1px solid var(--border);
    border-radius: 5px;
    padding: 3px 7px;
    font-size: 12px;
    color: var(--muted);
    cursor: pointer;
  }
  .action-btn:hover { color: var(--text); border-color: var(--accent); }
  .action-btn.danger:hover { color: var(--err-fg); border-color: var(--err-border); }

  /* ── empty / loading ── */
  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: 12px;
    height: 100%;
    color: var(--muted);
    text-align: center;
    padding: 40px;
  }
  .empty-state.small { height: 200px; }
  .empty-state p { margin: 0; font-size: 13px; line-height: 1.6; }
  .center { text-align: center; padding: 40px; }

  /* ── spinner ── */
  .spinner {
    width: 12px; height: 12px;
    border: 2px solid rgba(255,255,255,0.4);
    border-top-color: #fff;
    border-radius: 50%;
    display: inline-block;
    animation: spin 0.6s linear infinite;
  }
  @keyframes spin { to { transform: rotate(360deg); } }

  /* ── utils ── */
  .muted { color: var(--muted); }
  .mono  { font-family: var(--mono); }
  .small { font-size: 12px; margin: 6px 12px; }
  .err   { color: var(--err-fg); }

  /* ── modals ── */
  .modal-backdrop {
    position: fixed; inset: 0; z-index: 30;
    background: rgba(0,0,0,0.4);
    display: flex; align-items: center; justify-content: center; padding: 24px;
  }
  .modal {
    width: min(460px, 100%);
    display: flex; flex-direction: column;
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 10px;
    box-shadow: 0 10px 40px rgba(0,0,0,0.3);
    overflow: hidden;
  }
  .del-modal { width: min(400px, 100%); }
  .modal-head {
    display: flex; align-items: center; justify-content: space-between;
    padding: 12px 14px; border-bottom: 1px solid var(--border);
  }
  .modal-body { padding: 14px; display: flex; flex-direction: column; gap: 12px; }
  .modal-foot {
    display: flex; align-items: center; gap: 10px;
    padding: 10px 14px; border-top: 1px solid var(--border);
  }
  .grow { flex: 1; }
  .field { display: flex; flex-direction: column; gap: 4px; }
  .flabel { font-size: 12px; font-weight: 600; }
  .field input[type=text], .field input:not([type]) {
    padding: 7px 10px; font-size: 13px; font-family: var(--mono);
    color: var(--text); background: var(--panel);
    border: 1px solid var(--border); border-radius: 6px;
  }
  .field input:focus { outline: none; border-color: var(--accent); }
  .check-field {
    display: flex; align-items: center; gap: 8px;
    font-size: 13px; color: var(--text); cursor: pointer;
  }
  .del-msg { margin: 0; font-size: 13px; line-height: 1.6; color: var(--text); }
  .del-msg code {
    font-family: var(--mono); font-size: 12px;
    background: var(--panel-alt); padding: 1px 5px; border-radius: 4px;
  }
  .x {
    background: none; border: none; color: var(--muted);
    cursor: pointer; font-size: 13px;
  }
  .x:hover { color: var(--err-fg); }
  .ghost {
    background: none; border: 1px solid var(--border); border-radius: 6px;
    color: var(--text); padding: 6px 12px; font-size: 13px; cursor: pointer;
  }
  .modal-foot button:not(.ghost):not(.del-btn) {
    background: var(--accent); color: #fff; border: none;
    border-radius: 6px; padding: 7px 14px; font-size: 13px; cursor: pointer;
  }
  .del-btn {
    background: var(--err-fg, #ef4444); color: #fff; border: none;
    border-radius: 6px; padding: 7px 14px; font-size: 13px; font-weight: 600; cursor: pointer;
  }
  .del-btn:hover { opacity: 0.88; }
  .del-btn:disabled, .modal-foot button:disabled { opacity: 0.5; cursor: default; }
</style>

// src/components/StoragePanel.tsx
import { useEffect, useRef, useState } from 'react';
import { Database, Plus, RefreshCw, Upload, Download, Link as LinkIcon, X } from 'lucide-react';
import { listBuckets, createBucket, deleteBucket, listObjects, uploadObject, deleteObject, getObjectUrl } from '@/lib/engine/api.js';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from './ui/dialog';
import { cn } from '@/lib/utils';

interface Bucket {
  name: string;
  public?: boolean;
}
interface StorageObject {
  key: string;
  size?: number;
  last_modified?: string | null;
  content_type?: string;
}
interface Folder {
  key: string;
  name: string;
}

function fmtSize(bytes: number | undefined) {
  if (bytes == null) return '—';
  if (bytes >= 1_073_741_824) return `${(bytes / 1_073_741_824).toFixed(1)} GB`;
  if (bytes >= 1_048_576) return `${(bytes / 1_048_576).toFixed(1)} MB`;
  if (bytes >= 1_024) return `${(bytes / 1_024).toFixed(1)} KB`;
  return `${bytes} B`;
}
function fmtDate(iso: string | null | undefined) {
  if (!iso) return '—';
  const d = new Date(iso);
  const diff = Date.now() - d.getTime();
  if (diff < 60_000) return 'just now';
  if (diff < 3_600_000) return `${Math.floor(diff / 60_000)}m ago`;
  if (diff < 86_400_000) return `${Math.floor(diff / 3_600_000)}h ago`;
  if (diff < 7 * 86_400_000) return `${Math.floor(diff / 86_400_000)}d ago`;
  return d.toLocaleDateString();
}
function fileIcon(key: string) {
  const ext = key.split('.').pop()?.toLowerCase() ?? '';
  if (['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'avif'].includes(ext)) return '🖼';
  if (['mp4', 'mov', 'avi', 'mkv', 'webm'].includes(ext)) return '🎬';
  if (['mp3', 'wav', 'ogg', 'flac'].includes(ext)) return '🎵';
  if (ext === 'pdf') return '📄';
  if (['zip', 'tar', 'gz', 'bz2', '7z'].includes(ext)) return '🗜';
  if (['json', 'yaml', 'yml', 'toml', 'xml'].includes(ext)) return '📋';
  if (['js', 'ts', 'py', 'rs', 'go', 'java', 'cpp', 'c', 'sql'].includes(ext)) return '📝';
  return '📄';
}

export function StoragePanel() {
  const [supported, setSupported] = useState(true);
  const [buckets, setBuckets] = useState<Bucket[]>([]);
  const [bucketsLoading, setBucketsLoading] = useState(true);
  const [bucketsError, setBucketsError] = useState<string | null>(null);

  const [selectedBucket, setSelectedBucket] = useState<string | null>(null);
  const [prefix, setPrefix] = useState('');
  const [objects, setObjects] = useState<StorageObject[]>([]);
  const [folders, setFolders] = useState<Folder[]>([]);
  const [objLoading, setObjLoading] = useState(false);
  const [objError, setObjError] = useState<string | null>(null);

  const [newBucketOpen, setNewBucketOpen] = useState(false);
  const [newBucketName, setNewBucketName] = useState('');
  const [newBucketPublic, setNewBucketPublic] = useState(false);
  const [newBucketBusy, setNewBucketBusy] = useState(false);
  const [newBucketError, setNewBucketError] = useState<string | null>(null);

  const [deleteBucketTarget, setDeleteBucketTarget] = useState<string | null>(null);
  const [deleteBucketBusy, setDeleteBucketBusy] = useState(false);

  const [uploading, setUploading] = useState(false);
  const [uploadPct, setUploadPct] = useState(0);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [dragOver, setDragOver] = useState(false);

  const [deleteObjTarget, setDeleteObjTarget] = useState<string | null>(null);
  const [deleteObjBusy, setDeleteObjBusy] = useState(false);

  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  async function loadBuckets() {
    setBucketsLoading(true);
    setBucketsError(null);
    try {
      const out = await listBuckets();
      setSupported(out.supported);
      setBuckets(out.buckets);
    } catch (e: any) {
      setBucketsError(e?.message ?? String(e));
    } finally {
      setBucketsLoading(false);
    }
  }

  async function loadObjects(bucket: string, pfx: string) {
    setObjLoading(true);
    setObjError(null);
    try {
      const out = await listObjects(bucket, pfx);
      setFolders((out.prefixes ?? []).map((p: string) => ({ key: p, name: p.slice(pfx.length).replace(/\/$/, '') })));
      setObjects((out.objects ?? []).filter((o: StorageObject) => o.key !== pfx));
    } catch (e: any) {
      setObjError(e?.message ?? String(e));
      setFolders([]);
      setObjects([]);
    } finally {
      setObjLoading(false);
    }
  }

  useEffect(() => {
    loadBuckets();
  }, []);

  useEffect(() => {
    if (selectedBucket) loadObjects(selectedBucket, prefix);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedBucket, prefix]);

  function selectBucket(b: string) {
    setSelectedBucket(b);
    setPrefix('');
  }
  function openFolder(folderPrefix: string) {
    setPrefix(folderPrefix);
  }
  function navigateCrumb(idx: number) {
    const parts = prefix.split('/').filter(Boolean);
    setPrefix(parts.slice(0, idx + 1).join('/') + (idx >= 0 ? '/' : ''));
  }
  const crumbs = prefix
    .split('/')
    .filter(Boolean)
    .map((label, index) => ({ label, index }));

  async function submitNewBucket() {
    setNewBucketError(null);
    const n = newBucketName.trim();
    if (!n) {
      setNewBucketError('Bucket name is required');
      return;
    }
    setNewBucketBusy(true);
    try {
      await createBucket(n, { isPublic: newBucketPublic });
      setNewBucketOpen(false);
      setNewBucketName('');
      setNewBucketPublic(false);
      await loadBuckets();
    } catch (e: any) {
      setNewBucketError(e?.message ?? String(e));
    } finally {
      setNewBucketBusy(false);
    }
  }

  async function confirmDeleteBucket() {
    if (!deleteBucketTarget) return;
    setDeleteBucketBusy(true);
    try {
      await deleteBucket(deleteBucketTarget);
      if (selectedBucket === deleteBucketTarget) {
        setSelectedBucket(null);
        setPrefix('');
      }
      setDeleteBucketTarget(null);
      await loadBuckets();
    } catch (e: any) {
      setBucketsError(e?.message ?? String(e));
    } finally {
      setDeleteBucketBusy(false);
    }
  }

  function pickFiles() {
    fileInputRef.current?.click();
  }

  async function handleFiles(files: FileList | File[] | null | undefined) {
    if (!files || !('length' in files ? files.length : true) || !selectedBucket) return;
    const list = Array.from(files);
    if (!list.length) return;
    setUploading(true);
    setUploadError(null);
    try {
      for (const file of list) {
        setUploadPct(0);
        const key = prefix + file.name;
        await uploadObject(selectedBucket, key, file, (p: number) => setUploadPct(p));
      }
      await loadObjects(selectedBucket, prefix);
    } catch (e: any) {
      setUploadError(e?.message ?? String(e));
    } finally {
      setUploading(false);
      setUploadPct(0);
    }
  }

  function onFileInput(e: React.ChangeEvent<HTMLInputElement>) {
    handleFiles(e.target.files);
    e.target.value = '';
  }
  function onDrop(e: React.DragEvent) {
    e.preventDefault();
    setDragOver(false);
    handleFiles(e.dataTransfer.files);
  }

  async function confirmDeleteObj() {
    if (!deleteObjTarget || !selectedBucket) return;
    setDeleteObjBusy(true);
    try {
      await deleteObject(selectedBucket, deleteObjTarget);
      setDeleteObjTarget(null);
      await loadObjects(selectedBucket, prefix);
    } catch (e: any) {
      setObjError(e?.message ?? String(e));
    } finally {
      setDeleteObjBusy(false);
    }
  }

  async function copyUrl(key: string) {
    if (!selectedBucket) return;
    try {
      const url = await getObjectUrl(selectedBucket, key);
      await navigator.clipboard.writeText(url);
      setCopiedKey(key);
      setTimeout(() => setCopiedKey((k) => (k === key ? null : k)), 2000);
    } catch (e: any) {
      setObjError(e?.message ?? String(e));
    }
  }
  async function downloadObj(key: string) {
    if (!selectedBucket) return;
    try {
      const url = await getObjectUrl(selectedBucket, key);
      const a = document.createElement('a');
      a.href = url;
      a.download = key.split('/').pop() ?? key;
      a.click();
    } catch (e: any) {
      setObjError(e?.message ?? String(e));
    }
  }

  if (!supported) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-3 text-center text-text-light">
        <Database className="size-10 opacity-60" />
        <h3 className="m-0 text-lg font-medium text-foreground">Storage not available</h3>
        <p className="m-0 text-md leading-relaxed">
          The unidb engine doesn't expose <code>GET /storage/buckets</code> yet.
          <br />
          Wire up the MinIO proxy in the engine to enable object storage.
        </p>
      </div>
    );
  }

  return (
    <div className="flex h-full min-h-0">
      <aside className="flex w-56 shrink-0 flex-col overflow-hidden border-r border-border bg-surface">
        <div className="flex items-center gap-1 border-b border-border px-3 py-2.5">
          <span className="flex-1 text-xs font-bold tracking-wide text-text-muted uppercase">Buckets</span>
          <button
            className="flex size-[22px] items-center justify-center rounded-sm border border-border text-text-light hover:border-border-strong hover:text-foreground"
            title="New bucket"
            onClick={() => setNewBucketOpen(true)}
          >
            <Plus className="size-3.5" />
          </button>
          <button
            className="flex size-[22px] items-center justify-center rounded-sm border border-border text-text-light hover:border-border-strong hover:text-foreground"
            title="Refresh"
            onClick={loadBuckets}
          >
            <RefreshCw className="size-3.5" />
          </button>
        </div>

        {bucketsError ? (
          <p className="m-1.5 text-sm text-error">{bucketsError}</p>
        ) : bucketsLoading ? (
          <p className="m-1.5 text-sm text-text-light">Loading…</p>
        ) : buckets.length === 0 ? (
          <p className="m-1.5 text-sm text-text-light">No buckets yet.</p>
        ) : (
          <ul className="flex-1 list-none overflow-y-auto py-1.5">
            {buckets.map((b) => {
              const name = b.name ?? (b as any);
              const isActive = selectedBucket === name;
              return (
                <li key={name} className={cn('group mx-1 my-px flex items-center rounded-md px-1.5', isActive && 'bg-brand')}>
                  <button
                    className={cn('flex flex-1 items-center gap-1.5 py-1.5 text-left text-md', isActive ? 'text-brand-text-on' : 'text-foreground')}
                    onClick={() => selectBucket(name)}
                  >
                    <Database className="size-3.5 shrink-0" />
                    <span className="truncate">{name}</span>
                    {b.public && <span className="shrink-0 rounded-sm bg-info/15 px-1 text-[9px] font-bold text-info uppercase">public</span>}
                  </button>
                  <button
                    className={cn('shrink-0 px-1 text-sm opacity-0 group-hover:opacity-100', isActive ? 'text-brand-text-on/70' : 'text-text-muted hover:text-error')}
                    title="Delete bucket"
                    onClick={(e) => {
                      e.stopPropagation();
                      setDeleteBucketTarget(name);
                    }}
                  >
                    <X className="size-3" />
                  </button>
                </li>
              );
            })}
          </ul>
        )}
      </aside>

      <div className="flex min-w-0 flex-1 flex-col overflow-hidden">
        {!selectedBucket ? (
          <div className="flex h-full flex-col items-center justify-center gap-3 p-10 text-center text-text-light">
            <Database className="size-12 opacity-50" />
            <p className="m-0 text-md">Select a bucket to browse objects</p>
          </div>
        ) : (
          <>
            <div className="flex shrink-0 items-center gap-2 border-b border-border px-4 py-2.5">
              <nav className="flex min-w-0 flex-1 items-center gap-0.5 overflow-hidden text-md">
                <button
                  className="rounded-sm px-1 py-0.5 font-semibold whitespace-nowrap text-brand hover:bg-accent"
                  onClick={() => setPrefix('')}
                >
                  {selectedBucket}
                </button>
                {crumbs.map((c) => (
                  <span key={c.index} className="flex items-center gap-0.5">
                    <span className="px-0.5 text-text-muted">/</span>
                    <button className="rounded-sm px-1 py-0.5 font-semibold hover:bg-accent" onClick={() => navigateCrumb(c.index)}>
                      {c.label}
                    </button>
                  </span>
                ))}
              </nav>
              <span className="flex-1" />
              <input ref={fileInputRef} type="file" multiple className="hidden" onChange={onFileInput} />
              <button
                className="flex h-8 items-center gap-1.5 rounded-md bg-brand px-3.5 text-md font-medium whitespace-nowrap text-brand-text-on hover:bg-brand-hover disabled:opacity-60"
                onClick={pickFiles}
                disabled={uploading}
              >
                {uploading ? (
                  <>
                    <span className="size-3 animate-spin rounded-full border-2 border-brand-text-on/40 border-t-brand-text-on" />
                    {Math.round(uploadPct * 100)}%
                  </>
                ) : (
                  <>
                    <Upload className="size-3.5" /> Upload
                  </>
                )}
              </button>
              <button
                className="flex h-8 items-center justify-center rounded-md border border-border bg-secondary px-2 text-text-light hover:border-border-strong disabled:opacity-60"
                onClick={() => loadObjects(selectedBucket, prefix)}
                disabled={objLoading}
              >
                <RefreshCw className="size-3.5" />
              </button>
            </div>

            {uploadError && <p className="mx-4 mt-2 text-sm text-error">{uploadError}</p>}
            {objError && <p className="mx-4 mt-2 text-sm text-error">{objError}</p>}

            <div
              className="relative flex-1 overflow-auto"
              onDragOver={(e) => {
                e.preventDefault();
                setDragOver(true);
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={onDrop}
              role="region"
              aria-label="Drop files to upload"
            >
              {dragOver && (
                <div className="pointer-events-none absolute inset-1 rounded-lg border-2 border-dashed border-brand bg-brand-subtle" />
              )}
              {objLoading ? (
                <p className="p-10 text-center text-md text-text-light">Loading…</p>
              ) : folders.length === 0 && objects.length === 0 ? (
                <div className="flex h-52 flex-col items-center justify-center p-10 text-center">
                  <p className="m-0 text-md text-text-light">
                    This {prefix ? 'folder' : 'bucket'} is empty.
                    <br />
                    <span className="text-text-muted">Drag files here or click Upload.</span>
                  </p>
                </div>
              ) : (
                <table className="w-full border-collapse text-md">
                  <thead>
                    <tr>
                      <th className="sticky top-0 z-1 bg-card px-3 py-2 text-left text-xs font-semibold tracking-wide text-text-muted uppercase">Name</th>
                      <th className="sticky top-0 z-1 bg-card px-3 py-2 text-right text-xs font-semibold tracking-wide text-text-muted uppercase">Size</th>
                      <th className="sticky top-0 z-1 bg-card px-3 py-2 text-left text-xs font-semibold tracking-wide text-text-muted uppercase">Modified</th>
                      <th className="sticky top-0 z-1 bg-card px-3 py-2 text-left text-xs font-semibold tracking-wide text-text-muted uppercase">Type</th>
                      <th className="sticky top-0 z-1 bg-card px-3 py-2" />
                    </tr>
                  </thead>
                  <tbody>
                    {folders.map((f) => (
                      <tr key={f.key} className="border-b border-border-muted hover:bg-secondary" onDoubleClick={() => openFolder(f.key)}>
                        <td className="px-3 py-2">
                          <button className="flex items-center gap-2 font-medium text-brand hover:underline" onClick={() => openFolder(f.key)}>
                            <span>📁</span>
                            {f.name}/
                          </button>
                        </td>
                        <td className="px-3 py-2 text-right text-text-muted">—</td>
                        <td className="px-3 py-2 text-text-muted">—</td>
                        <td className="px-3 py-2 text-text-muted">folder</td>
                        <td />
                      </tr>
                    ))}
                    {objects.map((o) => {
                      const shortName = o.key.slice(prefix.length);
                      return (
                        <tr key={o.key} className="border-b border-border-muted hover:bg-secondary">
                          <td className="max-w-[400px] px-3 py-2">
                            <div className="flex items-center gap-2">
                              <span className="shrink-0">{fileIcon(o.key)}</span>
                              <span className="truncate" title={o.key}>
                                {shortName}
                              </span>
                            </div>
                          </td>
                          <td className="px-3 py-2 text-right font-mono">{fmtSize(o.size)}</td>
                          <td className="px-3 py-2 text-text-muted">{fmtDate(o.last_modified)}</td>
                          <td className="max-w-[100px] truncate px-3 py-2 text-xs text-text-muted" title={o.content_type}>
                            {o.content_type?.split('/')[1] ?? '—'}
                          </td>
                          <td className="px-3 py-2">
                            <div className="flex items-center gap-1 whitespace-nowrap">
                              <button className="rounded-md border border-border p-1 text-text-muted hover:border-border-strong hover:text-foreground" title="Download" onClick={() => downloadObj(o.key)}>
                                <Download className="size-3" />
                              </button>
                              <button
                                className="rounded-md border border-border p-1 text-text-muted hover:border-border-strong hover:text-foreground"
                                title={copiedKey === o.key ? 'Copied!' : 'Copy URL'}
                                onClick={() => copyUrl(o.key)}
                              >
                                {copiedKey === o.key ? '✓' : <LinkIcon className="size-3" />}
                              </button>
                              <button
                                className="rounded-md border border-border p-1 text-text-muted hover:border-error hover:text-error"
                                title="Delete"
                                onClick={() => setDeleteObjTarget(o.key)}
                              >
                                <X className="size-3" />
                              </button>
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              )}
            </div>
          </>
        )}
      </div>

      <Dialog open={newBucketOpen} onOpenChange={setNewBucketOpen}>
        <DialogContent className="max-w-[460px] p-0">
          <DialogHeader className="border-b border-border px-4 py-3">
            <DialogTitle>New bucket</DialogTitle>
          </DialogHeader>
          <div className="flex flex-col gap-3 p-4">
            <label className="flex flex-col gap-1">
              <span className="text-sm font-semibold">Bucket name</span>
              <input
                value={newBucketName}
                onChange={(e) => setNewBucketName(e.target.value)}
                placeholder="e.g. my-assets"
                spellCheck={false}
                onKeyDown={(e) => e.key === 'Enter' && submitNewBucket()}
                className="h-8 rounded-md border border-border bg-secondary px-2 font-mono text-md outline-none focus-visible:border-border-strong focus-visible:ring-[2px] focus-visible:ring-ring/40"
              />
            </label>
            <label className="flex items-center gap-2 text-md">
              <input type="checkbox" checked={newBucketPublic} onChange={(e) => setNewBucketPublic(e.target.checked)} />
              Public bucket (objects accessible without auth)
            </label>
            {newBucketError && <p className="m-0 text-sm text-error">{newBucketError}</p>}
          </div>
          <DialogFooter className="border-t border-border px-4 py-3">
            <button className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong" onClick={() => setNewBucketOpen(false)}>
              Cancel
            </button>
            <button
              className="h-8 rounded-md bg-brand px-3 text-md text-brand-text-on hover:bg-brand-hover disabled:opacity-45"
              onClick={submitNewBucket}
              disabled={newBucketBusy}
            >
              {newBucketBusy ? 'Creating…' : 'Create bucket'}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!deleteBucketTarget} onOpenChange={(open) => !open && setDeleteBucketTarget(null)}>
        <DialogContent className="max-w-[400px] p-0">
          <DialogHeader className="border-b border-border px-4 py-3">
            <DialogTitle>Delete bucket</DialogTitle>
          </DialogHeader>
          <div className="p-4">
            <p className="m-0 text-md leading-relaxed">
              Permanently delete bucket <code className="rounded-sm border border-border bg-secondary px-1 font-mono text-sm">{deleteBucketTarget}</code> and{' '}
              <strong>all its objects</strong>? This cannot be undone.
            </p>
          </div>
          <DialogFooter className="border-t border-border px-4 py-3">
            <button className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong" onClick={() => setDeleteBucketTarget(null)}>
              Cancel
            </button>
            <button
              className="h-8 rounded-md bg-error px-3 text-md font-semibold text-background hover:brightness-110 disabled:opacity-45"
              onClick={confirmDeleteBucket}
              disabled={deleteBucketBusy}
            >
              {deleteBucketBusy ? 'Deleting…' : 'Delete bucket'}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!deleteObjTarget} onOpenChange={(open) => !open && setDeleteObjTarget(null)}>
        <DialogContent className="max-w-[400px] p-0">
          <DialogHeader className="border-b border-border px-4 py-3">
            <DialogTitle>Delete object</DialogTitle>
          </DialogHeader>
          <div className="p-4">
            <p className="m-0 text-md leading-relaxed">
              Permanently delete <code className="rounded-sm border border-border bg-secondary px-1 font-mono text-sm">{deleteObjTarget?.split('/').pop()}</code>?
            </p>
          </div>
          <DialogFooter className="border-t border-border px-4 py-3">
            <button className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong" onClick={() => setDeleteObjTarget(null)}>
              Cancel
            </button>
            <button
              className="h-8 rounded-md bg-error px-3 text-md font-semibold text-background hover:brightness-110 disabled:opacity-45"
              onClick={confirmDeleteObj}
              disabled={deleteObjBusy}
            >
              {deleteObjBusy ? 'Deleting…' : 'Delete'}
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
