// src/components/LogsPanel.tsx
import { useState } from 'react';
import { Search, ChevronLeft, ChevronRight, ChevronDown } from 'lucide-react';
import { getLogs } from '@/lib/engine/api.js';
import { ErrorBox } from './ErrorBox';
import { TimeRangePicker } from './TimeRangePicker';
import type { CatalogError } from '@/hooks/useCatalog';
import { cn } from '@/lib/utils';

interface LogRow {
  timestamp?: string;
  level?: string;
  target?: string;
  message?: string;
  msg?: string;
  raw?: string;
  fields?: Record<string, unknown>;
  [key: string]: unknown;
}

const HIST_N = 48;
const LEVEL_ORDER = ['ERROR', 'WARN', 'INFO', 'DEBUG', 'TRACE'];

function countBy(arr: LogRow[], fn: (r: LogRow) => string) {
  const m: Record<string, number> = {};
  for (const x of arr) {
    const k = fn(x);
    m[k] = (m[k] ?? 0) + 1;
  }
  return m;
}

function levelColor(l: string | undefined) {
  const u = String(l ?? '').toUpperCase();
  if (u === 'ERROR') return 'var(--error)';
  if (u === 'WARN') return 'var(--warn)';
  if (u === 'DEBUG' || u === 'TRACE') return 'var(--text-muted)';
  return 'var(--brand)';
}
function levelTextClass(l: string | undefined) {
  const u = String(l ?? '').toUpperCase();
  if (u === 'ERROR') return 'text-error';
  if (u === 'WARN') return 'text-warn';
  if (u === 'DEBUG' || u === 'TRACE') return 'text-text-muted';
  return 'text-brand';
}
function getMsg(row: LogRow) {
  return (row.fields?.message as string) ?? row.message ?? row.msg ?? row.raw ?? '';
}
function fmtTs(ts: string | undefined) {
  if (!ts) return '';
  try {
    return new Date(ts).toLocaleString(undefined, { hour12: false });
  } catch {
    return ts;
  }
}
function extras(row: LogRow) {
  const { timestamp: _t, level: _l, target: _tg, message, msg, raw, fields, ...rest } = row;
  const merged: Record<string, unknown> = { ...(fields ?? {}), ...rest };
  if (message !== undefined) merged.message = message;
  if (msg !== undefined) merged.msg = msg;
  return merged;
}

function buildHist(logs: LogRow[], since: string, until: string, n: number) {
  const t0 = since ? new Date(since).getTime() : null;
  const t1 = until ? new Date(until).getTime() : Date.now();
  if (!t0 || !logs.length) return new Array(n).fill(0);
  const span = t1 - t0;
  if (span <= 0) return new Array(n).fill(0);
  const bms = span / n;
  const counts = new Array(n).fill(0);
  for (const log of logs) {
    if (!log.timestamp) continue;
    const t = new Date(log.timestamp).getTime();
    const idx = Math.min(Math.floor((t - t0) / bms), n - 1);
    if (idx >= 0) counts[idx]++;
  }
  return counts;
}

// Real clock-hour boundaries aligned to the time range. Step adapts to span
// so labels never crowd: 10m / 30m / 1h / 2h / 6h / 12h / 24h.
function buildTimeLabels(since: string, until: string) {
  const t0 = since ? new Date(since).getTime() : null;
  const t1 = until ? new Date(until).getTime() : Date.now();
  if (!t0) return [] as { pct: number; label: string }[];
  const span = t1 - t0;
  const spanH = span / 3_600_000;
  const stepH = spanH <= 1 ? 1 / 6 : spanH <= 3 ? 0.5 : spanH <= 12 ? 1 : spanH <= 48 ? 2 : spanH <= 168 ? 6 : spanH <= 336 ? 12 : 24;
  const stepMs = stepH * 3_600_000;
  const first = Math.ceil(t0 / stepMs) * stepMs;
  const out: { pct: number; label: string }[] = [];
  for (let t = first; t <= t1; t += stepMs) {
    const pct = ((t - t0) / span) * 100;
    const d = new Date(t);
    const hh = String(d.getHours()).padStart(2, '0');
    const mm = String(d.getMinutes()).padStart(2, '0');
    out.push({ pct, label: stepH >= 1 ? `${hh}:00` : `${hh}:${mm}` });
  }
  return out;
}

export function LogsPanel() {
  const [since, setSince] = useState(new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());
  const [until, setUntil] = useState('');
  const [q, setQ] = useState('');
  const [limit, setLimit] = useState(200);

  const [excLevels, setExcLevels] = useState<Set<string>>(new Set());
  const [excTargets, setExcTargets] = useState<Set<string>>(new Set());

  const [logs, setLogs] = useState<LogRow[]>([]);
  const [cursor, setCursor] = useState<string | null>(null);
  const [scanned, setScanned] = useState(0);
  const [truncated, setTruncated] = useState(false);
  const [supported, setSupported] = useState(true);
  const [error, setError] = useState<CatalogError | null>(null);
  const [loading, setLoading] = useState(false);
  const [expanded, setExpanded] = useState<Set<number>>(new Set());

  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [secTime, setSecTime] = useState(true);
  const [secType, setSecType] = useState(true);
  const [secLevel, setSecLevel] = useState(true);

  const targetCounts = countBy(logs, (r) => r.target ?? '');
  const levelCounts = countBy(logs, (r) => (r.level ?? '').toUpperCase());
  const allTargets = Object.keys(targetCounts).sort();
  const allLevels = LEVEL_ORDER.filter((l) => levelCounts[l]);

  const visible = logs.filter((r) => {
    if (excLevels.size && excLevels.has((r.level ?? '').toUpperCase())) return false;
    if (excTargets.size && excTargets.has(r.target ?? '')) return false;
    return true;
  });

  const histogram = buildHist(logs, since, until, HIST_N);
  const histMax = Math.max(...histogram, 1);
  const timeLabels = buildTimeLabels(since, until);

  function toggleExc(set: Set<string>, key: string) {
    const n = new Set(set);
    n.has(key) ? n.delete(key) : n.add(key);
    return n;
  }

  async function search({ append = false } = {}) {
    setLoading(true);
    setError(null);
    try {
      const out = await getLogs({ since: since || undefined, until: until || undefined, q: q || undefined, limit, cursor: append ? (cursor ?? undefined) : undefined });
      setSupported(out.supported);
      if (!out.supported) {
        setLogs([]);
        return;
      }
      setLogs((prev) => (append ? [...prev, ...out.logs] : out.logs));
      setCursor(out.next_cursor);
      setScanned(out.scanned);
      setTruncated(out.truncated);
      if (!append) {
        setExpanded(new Set());
        setExcLevels(new Set());
        setExcTargets(new Set());
      }
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
    } finally {
      setLoading(false);
    }
  }

  function onTimeApply({ since: s, until: u }: { since: string; until: string }) {
    setSince(s);
    setUntil(u);
    // Fetch with the new range explicitly — state updates are async, so
    // `search()` itself always reads the params it needs from its own args
    // rather than relying on `since`/`until` having flushed yet.
    searchWithRange(s, u);
  }

  async function searchWithRange(s: string, u: string) {
    setLoading(true);
    setError(null);
    try {
      const out = await getLogs({ since: s || undefined, until: u || undefined, q: q || undefined, limit });
      setSupported(out.supported);
      if (!out.supported) {
        setLogs([]);
        return;
      }
      setLogs(out.logs);
      setCursor(out.next_cursor);
      setScanned(out.scanned);
      setTruncated(out.truncated);
      setExpanded(new Set());
      setExcLevels(new Set());
      setExcTargets(new Set());
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
    } finally {
      setLoading(false);
    }
  }

  function toggle(i: number) {
    const n = new Set(expanded);
    n.has(i) ? n.delete(i) : n.add(i);
    setExpanded(n);
  }

  return (
    <div className="relative flex h-full gap-0 overflow-hidden">
      <button
        className="absolute top-2.5 left-0 z-10 flex size-[22px] items-center justify-center rounded-sm border border-border bg-card text-text-muted transition-transform hover:border-border-strong hover:text-foreground"
        style={{ transform: sidebarOpen ? 'translateX(210px)' : 'translateX(4px)' }}
        onClick={() => setSidebarOpen((v) => !v)}
        title={sidebarOpen ? 'Collapse filters' : 'Expand filters'}
        aria-label={sidebarOpen ? 'Collapse filters' : 'Expand filters'}
      >
        {sidebarOpen ? <ChevronLeft className="size-3.5" /> : <ChevronRight className="size-3.5" />}
      </button>

      <aside
        className={cn('flex flex-col overflow-y-auto border-r border-border pb-6 transition-[width,opacity]', sidebarOpen ? 'w-[232px]' : 'w-0 overflow-hidden border-r-0 p-0 opacity-0')}
      >
        <div className="border-b border-border-muted">
          <button className="flex w-full items-center gap-1.5 px-3.5 py-2 text-left text-md font-semibold hover:bg-accent" onClick={() => setSecTime((v) => !v)}>
            <span className="flex-1">Time Range</span>
            <ChevronDown className={cn('size-3 opacity-50 transition-transform', secTime && 'rotate-180')} />
          </button>
          {secTime && (
            <div className="px-3.5 pb-2">
              <TimeRangePicker onApply={onTimeApply} />
            </div>
          )}
        </div>

        <div className="border-b border-border-muted">
          <button className="flex w-full items-center gap-1.5 px-3.5 py-2 text-left text-md font-semibold hover:bg-accent" onClick={() => setSecType((v) => !v)}>
            <span className="flex-1">Log Type</span>
            {excTargets.size > 0 && <span className="rounded-full bg-brand px-1.5 text-[10px] font-medium text-brand-text-on">{excTargets.size} hidden</span>}
            <ChevronDown className={cn('size-3 opacity-50 transition-transform', secType && 'rotate-180')} />
          </button>
          {secType && (
            <div className="pb-2">
              {!allTargets.length ? (
                <p className="m-0 px-3.5 py-1 text-sm text-text-muted">Run Search to populate.</p>
              ) : (
                allTargets.map((t) => (
                  <label key={t} className="flex items-center gap-1.5 px-3.5 py-1 text-md hover:bg-accent">
                    <input type="checkbox" checked={!excTargets.has(t)} onChange={() => setExcTargets((s) => toggleExc(s, t))} />
                    <span className="flex-1 truncate font-mono text-sm">{t || '(unknown)'}</span>
                    <span className="min-w-6 text-right text-xs text-text-muted">{targetCounts[t] ?? 0}</span>
                  </label>
                ))
              )}
            </div>
          )}
        </div>

        <div>
          <button className="flex w-full items-center gap-1.5 px-3.5 py-2 text-left text-md font-semibold hover:bg-accent" onClick={() => setSecLevel((v) => !v)}>
            <span className="flex-1">Level</span>
            {excLevels.size > 0 && <span className="rounded-full bg-brand px-1.5 text-[10px] font-medium text-brand-text-on">{excLevels.size} hidden</span>}
            <ChevronDown className={cn('size-3 opacity-50 transition-transform', secLevel && 'rotate-180')} />
          </button>
          {secLevel && (
            <div className="pb-2">
              {!allLevels.length ? (
                <p className="m-0 px-3.5 py-1 text-sm text-text-muted">Run Search to populate.</p>
              ) : (
                allLevels.map((lv) => (
                  <label key={lv} className="flex items-center gap-1.5 px-3.5 py-1 text-md hover:bg-accent">
                    <input type="checkbox" checked={!excLevels.has(lv)} onChange={() => setExcLevels((s) => toggleExc(s, lv))} />
                    <span className="size-2 shrink-0 rounded-sm" style={{ background: levelColor(lv) }} />
                    <span className="flex-1 text-sm">{lv}</span>
                    <span className="min-w-6 text-right text-xs text-text-muted">{levelCounts[lv] ?? 0}</span>
                  </label>
                ))
              )}
            </div>
          )}
        </div>
      </aside>

      <div className="flex min-h-0 min-w-0 flex-1 flex-col gap-2.5 overflow-hidden pl-[30px]">
        <div className="flex items-center gap-2">
          <div className="flex flex-1 items-center gap-2 rounded-md border border-border bg-card px-2.5 py-1.5">
            <Search className="size-3.5 shrink-0 opacity-40" />
            <input
              className="flex-1 bg-transparent text-md text-foreground outline-none"
              type="text"
              placeholder="Search logs…"
              value={q}
              onChange={(e) => setQ(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && search()}
            />
          </div>
          <label className="flex items-center gap-1.5 text-sm whitespace-nowrap text-text-muted">
            Limit
            <input
              className="h-8 w-[60px] rounded-md border border-border bg-secondary px-1.5 text-md"
              type="number"
              min={1}
              max={500}
              value={limit}
              onChange={(e) => setLimit(Number(e.target.value))}
            />
          </label>
          <button
            className="h-8 rounded-md bg-brand px-3 text-md whitespace-nowrap text-brand-text-on hover:bg-brand-hover disabled:opacity-60"
            onClick={() => search()}
            disabled={loading}
          >
            {loading ? 'Searching…' : 'Search'}
          </button>
        </div>

        {error && (
          <>
            <ErrorBox error={error} />
            {error.status === 403 && (
              <p className="m-0 text-sm text-text-light">
                <code>/logs</code> is superuser-gated — use a superuser token.
              </p>
            )}
          </>
        )}

        {!supported ? (
          <p className="text-sm text-text-light">
            This server doesn't expose <code>GET /logs</code>. Rebuild from a build that includes item 22 (logs surface).
          </p>
        ) : (
          <>
            {logs.length > 0 && (
              <>
                <div className="overflow-visible rounded-md border border-border bg-secondary" aria-hidden="true">
                  <div className="px-0.5">
                    <svg className="block h-12 w-full rounded-t" viewBox={`0 0 ${HIST_N * 11} 48`} preserveAspectRatio="none">
                      {histogram.map((count, i) => {
                        const h = Math.max(count ? 3 : 0, Math.round((count / histMax) * 40));
                        return <rect key={i} x={i * 11 + 1} y={48 - h - 2} width={9} height={h} rx={1.5} fill="var(--brand)" opacity={count ? 0.65 : 0.1} />;
                      })}
                    </svg>
                    <div className="relative h-5 overflow-visible border-t border-border bg-secondary">
                      {timeLabels.map((lbl, i) => {
                        const isFirst = i === 0;
                        const isLast = i === timeLabels.length - 1;
                        const leftVal = isLast ? '100%' : `${lbl.pct}%`;
                        const tx = isFirst ? '0%' : isLast ? '-100%' : '-50%';
                        return (
                          <span
                            key={i}
                            className="absolute top-[3px] font-mono text-[10px] leading-none whitespace-nowrap text-text-muted"
                            style={{ left: leftVal, transform: `translateX(${tx})` }}
                          >
                            {lbl.label}
                          </span>
                        );
                      })}
                    </div>
                  </div>
                </div>
                <div className="flex gap-1.5 px-0.5 text-sm text-text-muted">
                  <span>
                    {visible.length}
                    {excLevels.size || excTargets.size ? ` of ${logs.length}` : ''} shown
                  </span>
                  <span>·</span>
                  <span>{scanned.toLocaleString()} scanned</span>
                  {truncated && <span>· scan budget hit</span>}
                </div>
              </>
            )}

            {visible.length > 0 ? (
              <>
                <div className="min-h-0 flex-1 overflow-auto rounded-md border border-border">
                  <table className="w-full table-fixed border-collapse font-mono text-sm">
                    <thead>
                      <tr>
                        <th className="w-14 bg-secondary px-2.5 py-1.5 text-left text-xs font-semibold text-text-muted">Level</th>
                        <th className="w-[152px] bg-secondary px-2.5 py-1.5 text-left text-xs font-semibold text-text-muted">Timestamp</th>
                        <th className="w-[148px] bg-secondary px-2.5 py-1.5 text-left text-xs font-semibold text-text-muted">Target</th>
                        <th className="bg-secondary px-2.5 py-1.5 text-left text-xs font-semibold text-text-muted">Message</th>
                      </tr>
                    </thead>
                    <tbody>
                      {visible.map((row, i) => (
                        <>
                          <tr
                            key={i}
                            className={cn('cursor-pointer border-b border-border hover:bg-secondary', expanded.has(i) && 'bg-secondary')}
                            role="button"
                            tabIndex={0}
                            onClick={() => toggle(i)}
                            onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && (e.preventDefault(), toggle(i))}
                          >
                            <td className="overflow-hidden px-2.5 py-1 whitespace-nowrap">
                              <span className={cn('text-xs font-bold', levelTextClass(row.level))}>{(row.level ?? '·').toUpperCase()}</span>
                            </td>
                            <td className="overflow-hidden px-2.5 py-1 text-xs text-text-muted whitespace-nowrap">{fmtTs(row.timestamp)}</td>
                            <td className="overflow-hidden px-2.5 py-1 text-sm text-brand/85 whitespace-nowrap">{row.target ?? ''}</td>
                            <td className="overflow-hidden px-2.5 py-1 whitespace-nowrap text-foreground">{getMsg(row)}</td>
                          </tr>
                          {expanded.has(i) && (
                            <tr className="border-b border-border bg-secondary">
                              <td colSpan={4} className="p-0">
                                <pre className="m-0 overflow-x-auto p-3 text-sm whitespace-pre">{JSON.stringify(extras(row), null, 2)}</pre>
                              </td>
                            </tr>
                          )}
                        </>
                      ))}
                    </tbody>
                  </table>
                </div>

                {cursor ? (
                  <button className="self-start py-1 text-md text-brand hover:underline disabled:opacity-60" onClick={() => search({ append: true })} disabled={loading}>
                    Load older →
                  </button>
                ) : (
                  <p className="text-center text-sm text-text-light">End of results.</p>
                )}
              </>
            ) : !loading && logs.length ? (
              <p className="text-sm text-text-light">All results filtered out — uncheck some filters on the left.</p>
            ) : !loading ? (
              <p className="text-sm text-text-light">No log lines. Set a time range and Search — results are newest-first.</p>
            ) : null}
          </>
        )}
      </div>
    </div>
  );
}

// src-v1/lib/LogsPanel.svelte
<script>
  import { getLogs } from './api.js';
  import ErrorBox from './ErrorBox.svelte';
  import TimeRangePicker from './TimeRangePicker.svelte';

  // ---- fetch params --------------------------------------------------------
  let since = $state(new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString());
  let until = $state('');
  let q     = $state('');
  let limit = $state(200);

  // ---- client-side exclusion filters (empty = show all) --------------------
  let excLevels  = $state(new Set());
  let excTargets = $state(new Set());

  // ---- data ----------------------------------------------------------------
  let logs      = $state([]);
  let cursor    = $state(null);
  let scanned   = $state(0);
  let truncated = $state(false);
  let supported = $state(true);
  let error     = $state(null);
  let loading   = $state(false);
  let expanded  = $state(new Set());

  // ---- sidebar section open/close ------------------------------------------
  let sidebarOpen = $state(true);
  let secTime  = $state(true);
  let secType  = $state(true);
  let secLevel = $state(true);

  // ---- derived -------------------------------------------------------------
  function countBy(arr, fn) {
    const m = {};
    for (const x of arr) { const k = fn(x); m[k] = (m[k] ?? 0) + 1; }
    return m;
  }

  let targetCounts = $derived(countBy(logs, r => r.target ?? ''));
  let levelCounts  = $derived(countBy(logs, r => (r.level ?? '').toUpperCase()));
  let allTargets   = $derived(Object.keys(targetCounts).sort());

  const LEVEL_ORDER = ['ERROR', 'WARN', 'INFO', 'DEBUG', 'TRACE'];
  let allLevels = $derived(LEVEL_ORDER.filter(l => levelCounts[l]));

  let visible = $derived(logs.filter(r => {
    if (excLevels.size  && excLevels.has((r.level ?? '').toUpperCase())) return false;
    if (excTargets.size && excTargets.has(r.target ?? ''))               return false;
    return true;
  }));

  // histogram: 48 narrow buckets across the fetched window
  const HIST_N = 48;
  let histogram  = $derived(buildHist(logs, since, until, HIST_N));
  let histMax    = $derived(Math.max(...histogram, 1));
  let timeLabels = $derived(buildTimeLabels(since, until));

  function buildHist(logs, since, until, n) {
    const t0 = since ? new Date(since).getTime() : null;
    const t1 = until ? new Date(until).getTime() : Date.now();
    if (!t0 || !logs.length) return new Array(n).fill(0);
    const span = t1 - t0;
    if (span <= 0) return new Array(n).fill(0);
    const bms = span / n;
    const counts = new Array(n).fill(0);
    for (const log of logs) {
      if (!log.timestamp) continue;
      const t = new Date(log.timestamp).getTime();
      const idx = Math.min(Math.floor((t - t0) / bms), n - 1);
      if (idx >= 0) counts[idx]++;
    }
    return counts;
  }

  // Real clock-hour boundaries aligned to the time range.
  // Step adapts to span so labels never crowd: 10m / 30m / 1h / 2h / 6h / 12h / 24h.
  function buildTimeLabels(since, until) {
    const t0 = since ? new Date(since).getTime() : null;
    const t1 = until ? new Date(until).getTime() : Date.now();
    if (!t0) return [];
    const span   = t1 - t0;
    const spanH  = span / 3_600_000;
    const stepH  = spanH <=  1 ? 1/6   // 10 min
                 : spanH <=  3 ? 0.5   // 30 min
                 : spanH <= 12 ? 1     // 1 h
                 : spanH <= 48 ? 2     // 2 h
                 : spanH <= 168 ? 6    // 6 h
                 : spanH <= 336 ? 12   // 12 h
                 : 24;                 // 24 h
    const stepMs = stepH * 3_600_000;
    // first mark: round up t0 to next stepMs boundary
    const first  = Math.ceil(t0 / stepMs) * stepMs;
    const out    = [];
    for (let t = first; t <= t1; t += stepMs) {
      const pct = ((t - t0) / span) * 100;
      const d   = new Date(t);
      const hh  = String(d.getHours()).padStart(2, '0');
      const mm  = String(d.getMinutes()).padStart(2, '0');
      out.push({ pct, label: stepH >= 1 ? `${hh}:00` : `${hh}:${mm}` });
    }
    return out;
  }

  // ---- helpers -------------------------------------------------------------
  function toggleExc(set, key) {
    const n = new Set(set);
    n.has(key) ? n.delete(key) : n.add(key);
    return n;
  }

  function levelColor(l) {
    const u = String(l ?? '').toUpperCase();
    if (u === 'ERROR') return '#ef4444';
    if (u === 'WARN')  return '#f59e0b';
    if (u === 'DEBUG' || u === 'TRACE') return '#9ca3af';
    return 'var(--accent)';
  }

  function levelClass(l) {
    const u = String(l ?? '').toUpperCase();
    if (u === 'ERROR') return 'lvl-error';
    if (u === 'WARN')  return 'lvl-warn';
    if (u === 'DEBUG' || u === 'TRACE') return 'lvl-dim';
    return 'lvl-info';
  }

  function getMsg(row) {
    return row.fields?.message ?? row.message ?? row.msg ?? row.raw ?? '';
  }

  function fmtTs(ts) {
    if (!ts) return '';
    try { return new Date(ts).toLocaleString(undefined, { hour12: false }); }
    catch { return ts; }
  }

  function extras(row) {
    const { timestamp, level: _l, target: _t, message, msg, raw, fields, ...rest } = row;
    const merged = { ...(fields ?? {}), ...rest };
    if (message !== undefined) merged.message = message;
    if (msg     !== undefined) merged.msg     = msg;
    return merged;
  }

  function toggle(i) {
    const n = new Set(expanded);
    n.has(i) ? n.delete(i) : n.add(i);
    expanded = n;
  }

  // ---- fetch ---------------------------------------------------------------
  async function search({ append = false } = {}) {
    loading = true; error = null;
    try {
      const out = await getLogs({
        since: since || undefined,
        until: until || undefined,
        q: q || undefined,
        limit,
        cursor: append ? cursor : undefined,
      });
      supported = out.supported;
      if (!out.supported) { logs = []; return; }
      logs      = append ? [...logs, ...out.logs] : out.logs;
      cursor    = out.next_cursor;
      scanned   = out.scanned;
      truncated = out.truncated;
      if (!append) { expanded = new Set(); excLevels = new Set(); excTargets = new Set(); }
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
    } finally {
      loading = false;
    }
  }

  function onTimeApply({ since: s, until: u }) {
    since = s; until = u;
    search();
  }
</script>

<div class="logs-layout">
  <!-- Sidebar collapse toggle -->
  <button
    class="sidebar-toggle"
    onclick={() => (sidebarOpen = !sidebarOpen)}
    title={sidebarOpen ? 'Collapse filters' : 'Expand filters'}
    aria-label={sidebarOpen ? 'Collapse filters' : 'Expand filters'}
  >
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.7">
      {#if sidebarOpen}
        <path d="M9 2L4 7l5 5"/>
      {:else}
        <path d="M5 2l5 5-5 5"/>
      {/if}
    </svg>
  </button>

  <!-- ===== SIDEBAR ===== -->
  <aside class="sidebar" class:hidden={!sidebarOpen}>

    <!-- Time Range -->
    <div class="sec">
      <button class="sec-hdr" onclick={() => (secTime = !secTime)}>
        <span>Time Range</span>
        <svg class="chevron {secTime ? 'open' : ''}" width="12" height="12" viewBox="0 0 12 12"
             fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">
          <path d="M2 4l4 4 4-4"/>
        </svg>
      </button>
      {#if secTime}
        <div class="sec-body">
          <TimeRangePicker onApply={onTimeApply} />
        </div>
      {/if}
    </div>

    <!-- Log Type (target) -->
    <div class="sec">
      <button class="sec-hdr" onclick={() => (secType = !secType)}>
        <span>Log Type</span>
        {#if excTargets.size}
          <span class="badge">{excTargets.size} hidden</span>
        {/if}
        <svg class="chevron {secType ? 'open' : ''}" width="12" height="12" viewBox="0 0 12 12"
             fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">
          <path d="M2 4l4 4 4-4"/>
        </svg>
      </button>
      {#if secType}
        <div class="sec-body">
          {#if !allTargets.length}
            <p class="sec-empty">Run Search to populate.</p>
          {:else}
            {#each allTargets as t}
              <label class="chk-row">
                <input type="checkbox"
                  checked={!excTargets.has(t)}
                  onchange={() => (excTargets = toggleExc(excTargets, t))}
                />
                <span class="chk-label">{t || '(unknown)'}</span>
                <span class="chk-count">{targetCounts[t] ?? 0}</span>
              </label>
            {/each}
          {/if}
        </div>
      {/if}
    </div>

    <!-- Level -->
    <div class="sec">
      <button class="sec-hdr" onclick={() => (secLevel = !secLevel)}>
        <span>Level</span>
        {#if excLevels.size}
          <span class="badge">{excLevels.size} hidden</span>
        {/if}
        <svg class="chevron {secLevel ? 'open' : ''}" width="12" height="12" viewBox="0 0 12 12"
             fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true">
          <path d="M2 4l4 4 4-4"/>
        </svg>
      </button>
      {#if secLevel}
        <div class="sec-body">
          {#if !allLevels.length}
            <p class="sec-empty">Run Search to populate.</p>
          {:else}
            {#each allLevels as lv}
              <label class="chk-row">
                <input type="checkbox"
                  checked={!excLevels.has(lv)}
                  onchange={() => (excLevels = toggleExc(excLevels, lv))}
                />
                <span class="lvl-dot" style="background:{levelColor(lv)}"></span>
                <span class="chk-label">{lv}</span>
                <span class="chk-count">{levelCounts[lv] ?? 0}</span>
              </label>
            {/each}
          {/if}
        </div>
      {/if}
    </div>

  </aside>

  <!-- ===== MAIN ===== -->
  <div class="main">

    <!-- Search bar -->
    <div class="search-bar">
      <div class="q-wrap">
        <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor"
             stroke-width="1.8" aria-hidden="true">
          <circle cx="6.5" cy="6.5" r="5"/>
          <path d="M10.5 10.5L14 14" stroke-linecap="round"/>
        </svg>
        <input class="q-input" type="text" placeholder="Search logs…" bind:value={q}
          onkeydown={(e) => e.key === 'Enter' && search()} />
      </div>
      <label class="limit-label">
        Limit
        <input class="limit-input" type="number" min="1" max="500" bind:value={limit} />
      </label>
      <button class="primary" onclick={() => search()} disabled={loading}>
        {loading ? 'Searching…' : 'Search'}
      </button>
    </div>

    {#if error}
      <ErrorBox {error} />
      {#if error.status === 403}
        <p class="muted"><code>/logs</code> is superuser-gated — use a superuser token.</p>
      {/if}
    {/if}

    {#if !supported}
      <p class="muted">This server doesn't expose <code>GET /logs</code>. Rebuild from a build that includes item 22 (logs surface).</p>
    {:else}

      <!-- Histogram -->
      {#if logs.length}
        <div class="hist-wrap" aria-hidden="true">
          <!-- bars with equal horizontal inset so both edges have breathing room -->
          <div class="hist-bars-pad">
            <svg class="hist-svg" viewBox="0 0 {HIST_N * 11} 48" preserveAspectRatio="none">
              {#each histogram as count, i}
                {@const h = Math.max(count ? 3 : 0, Math.round((count / histMax) * 40))}
                <rect
                  x={i * 11 + 1} y={48 - h - 2}
                  width="9" height={h}
                  rx="1.5"
                  fill="var(--accent)"
                  opacity={count ? 0.65 : 0.1}
                />
              {/each}
            </svg>
            <!-- time axis labels aligned inside the same padded region -->
            <div style="position:relative;height:20px;border-top:1px solid var(--border);background:var(--panel-alt);overflow:visible">
              {#each timeLabels as { pct, label }, i}
                {@const isFirst = i === 0}
                {@const isLast  = i === timeLabels.length - 1}
                {@const leftVal = isLast ? '100%' : `${pct}%`}
                {@const tx      = isFirst ? '0%' : isLast ? '-100%' : '-50%'}
                <span style="position:absolute;left:{leftVal};transform:translateX({tx});top:3px;font-size:10px;font-family:var(--mono);color:var(--muted);white-space:nowrap;line-height:1">{label}</span>
              {/each}
            </div>
          </div>
        </div>
        <!-- meta line sits below the card, not inside it -->
        <div class="hist-meta">
          <span>{visible.length}{excLevels.size || excTargets.size ? ` of ${logs.length}` : ''} shown</span>
          <span>·</span>
          <span>{scanned.toLocaleString()} scanned</span>
          {#if truncated}<span>· scan budget hit</span>{/if}
        </div>
      {/if}

      <!-- Log table -->
      {#if visible.length}
        <div class="table-wrap">
          <table class="log-table">
            <thead>
              <tr>
                <th class="col-lvl">Level</th>
                <th class="col-ts">Timestamp</th>
                <th class="col-target">Target</th>
                <th class="col-msg">Message</th>
              </tr>
            </thead>
            <tbody>
              {#each visible as row, i}
                <tr
                  class="log-row {expanded.has(i) ? 'is-open' : ''}"
                  role="button"
                  tabindex="0"
                  onclick={() => toggle(i)}
                  onkeydown={(e) => (e.key === 'Enter' || e.key === ' ') && (e.preventDefault(), toggle(i))}
                >
                  <td><span class="lvl {levelClass(row.level)}">{(row.level ?? '·').toUpperCase()}</span></td>
                  <td class="ts">{fmtTs(row.timestamp)}</td>
                  <td class="target">{row.target ?? ''}</td>
                  <td class="msg">{getMsg(row)}</td>
                </tr>
                {#if expanded.has(i)}
                  <tr class="detail-row">
                    <td colspan="4">
                      <pre class="detail">{JSON.stringify(extras(row), null, 2)}</pre>
                    </td>
                  </tr>
                {/if}
              {/each}
            </tbody>
          </table>
        </div>

        {#if cursor}
          <button class="link more" onclick={() => search({ append: true })} disabled={loading}>
            Load older →
          </button>
        {:else}
          <p class="muted end">End of results.</p>
        {/if}

      {:else if !loading && logs.length}
        <p class="muted">All results filtered out — uncheck some filters on the left.</p>
      {:else if !loading}
        <p class="muted">No log lines. Set a time range and Search — results are newest-first.</p>
      {/if}

    {/if}
  </div>
</div>

<style>
  /* ---- two-column layout — fills parent panel, no outer scroll ---- */
  .logs-layout {
    display: flex;
    gap: 0;
    height: 100%;
    overflow: hidden;
    position: relative;
  }

  /* sidebar collapse toggle */
  .sidebar-toggle {
    position: absolute;
    top: 10px;
    left: 0;
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 22px;
    height: 22px;
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 4px;
    cursor: pointer;
    color: var(--muted);
    padding: 0;
    transform: translateX(210px);
    transition: transform 0.2s;
  }
  .sidebar-toggle:hover { color: var(--text); border-color: var(--accent); }
  /* when sidebar is collapsed the button anchors to the left edge */
  :global(.logs-layout:has(.sidebar.hidden) .sidebar-toggle) {
    transform: translateX(4px);
  }

  /* ===== SIDEBAR ===== */
  .sidebar {
    width: 232px;
    flex-shrink: 0;
    border-right: 1px solid var(--border);
    display: flex;
    flex-direction: column;
    gap: 0;
    overflow-y: auto;
    padding-bottom: 24px;
    transition: width 0.2s, opacity 0.15s;
  }
  .sidebar.hidden {
    width: 0;
    overflow: hidden;
    opacity: 0;
    border-right: none;
    padding: 0;
  }

  .sec {
    border-bottom: 1px solid var(--border);
  }
  .sec-hdr {
    width: 100%;
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 9px 14px;
    background: none;
    border: none;
    text-align: left;
    font-size: 12.5px;
    font-weight: 600;
    color: var(--text);
    cursor: pointer;
  }
  .sec-hdr:hover { background: var(--panel-alt); }
  .sec-hdr span:first-child { flex: 1; }

  .chevron { transition: transform 0.15s; opacity: 0.5; }
  .chevron.open { transform: rotate(180deg); }

  .badge {
    font-size: 10px;
    font-weight: 500;
    background: var(--accent);
    color: #fff;
    border-radius: 8px;
    padding: 1px 6px;
  }

  .sec-body { padding: 4px 0 8px; }

  .sec-empty {
    font-size: 12px;
    color: var(--muted);
    padding: 4px 14px;
    margin: 0;
  }

  .chk-row {
    display: flex;
    align-items: center;
    gap: 7px;
    padding: 5px 14px;
    cursor: pointer;
    font-size: 12.5px;
    color: var(--text);
  }
  .chk-row:hover { background: var(--panel-alt); }
  .chk-row input[type="checkbox"] { cursor: pointer; accent-color: var(--accent); }
  .chk-label { flex: 1; font-family: var(--mono); font-size: 11.5px; }
  .chk-count {
    font-size: 11px;
    color: var(--muted);
    min-width: 24px;
    text-align: right;
  }
  .lvl-dot {
    width: 9px; height: 9px;
    border-radius: 2px;
    flex-shrink: 0;
  }

  /* ===== MAIN ===== */
  .main {
    flex: 1;
    min-width: 0;
    min-height: 0;
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding-left: 30px;  /* leaves room for the toggle button */
    overflow: hidden;
  }

  /* search bar */
  .search-bar {
    display: flex;
    gap: 8px;
    align-items: center;
  }
  .q-wrap {
    display: flex;
    align-items: center;
    gap: 8px;
    flex: 1;
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 6px 10px;
    background: var(--panel);
  }
  .q-wrap svg { opacity: 0.4; flex-shrink: 0; }
  .q-input {
    flex: 1;
    border: none;
    background: transparent;
    color: var(--text);
    font-size: 13px;
  }
  .q-input:focus { outline: none; }

  .limit-label {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 11.5px;
    color: var(--muted);
    white-space: nowrap;
  }
  .limit-input {
    width: 60px;
    padding: 5px 7px;
    border: 1px solid var(--border);
    border-radius: 5px;
    background: var(--panel);
    color: var(--text);
    font-size: 13px;
  }

  button.primary {
    background: var(--accent);
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 7px 14px;
    cursor: pointer;
    font-size: 13px;
    white-space: nowrap;
  }
  button.primary:disabled { opacity: 0.6; cursor: default; }

  /* histogram */
  .hist-wrap {
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel-alt);
    overflow: visible;
  }
  /* equal left/right inset so bars don't touch the card edges */
  .hist-bars-pad {
    padding: 0 2px;
  }
  .hist-svg {
    width: 100%;
    height: 48px;
    display: block;
    border-radius: 4px 4px 0 0;
  }
  /* meta line sits below the histogram card */
  .hist-meta {
    display: flex;
    gap: 6px;
    font-size: 11.5px;
    color: var(--muted);
    padding: 4px 2px 0;
  }

  /* log table — only this region scrolls */
  .table-wrap {
    flex: 1;
    min-height: 0;
    border: 1px solid var(--border);
    border-radius: 6px;
    overflow: auto;
  }
  .log-table {
    width: 100%;
    table-layout: fixed;          /* columns honour declared widths; msg gets the rest */
    border-collapse: collapse;
    font-family: var(--mono);
    font-size: 12.5px;
  }
  .log-table thead th {
    text-align: left;
    padding: 6px 10px;
    background: var(--panel-alt);
    border-bottom: 1px solid var(--border);
    font-size: 11px;
    font-weight: 600;
    color: var(--muted);
    overflow: hidden;
    white-space: nowrap;
  }
  .col-lvl    { width: 56px; }
  .col-ts     { width: 152px; }
  .col-target { width: 148px; }
  .col-msg    { /* fills all remaining width */ }

  .log-row { cursor: pointer; border-bottom: 1px solid var(--border); }
  .log-row:hover td,
  .log-row.is-open td { background: var(--panel-alt); }
  .log-row td {
    padding: 4px 10px;
    vertical-align: middle;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .log-row td.msg   { color: var(--text); }
  .log-row td.ts     { color: var(--muted); font-size: 12px; }
  .log-row td.target { color: var(--accent); opacity: 0.85; font-size: 12px; }

  .lvl         { display: inline-block; font-weight: 700; font-size: 11px; }
  .lvl-error   { color: var(--err-fg); }
  .lvl-warn    { color: #d99922; }
  .lvl-info    { color: var(--accent); }
  .lvl-dim     { color: var(--muted); }

  .detail-row td {
    padding: 0;
    border-bottom: 1px solid var(--border);
    background: var(--panel-alt);
  }
  .detail {
    margin: 0; padding: 8px 12px;
    font-size: 12px; overflow-x: auto; white-space: pre;
  }

  /* misc */
  .muted { color: var(--muted); font-size: 13px; }
  button.link { background: none; border: none; color: var(--accent); cursor: pointer; font-size: 13px; padding: 4px 0; }
  .more       { align-self: flex-start; }
  .end        { text-align: center; }
</style>
