// src/components/SqlEditor.tsx
import { useMemo, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import {
  runSql,
  explain,
  explainAnalyze,
  isSingleSelect,
  txnBegin,
  txnCommit,
  txnRollback,
  runSqlCursor,
  cursorPage,
  cursorClose,
} from '@/lib/engine/api.js';
import { embed, vectorToSql } from '@/lib/engine/embed.js';
import { DataGrid, type DataGridResult } from './DataGrid';
import { ErrorBox } from './ErrorBox';
import type { CatalogError } from '@/hooks/useCatalog';
import { cn } from '@/lib/utils';

interface Session {
  txnId: number | string;
  isolation: string;
}
interface StreamState {
  cursorId: string;
  columns: string[];
  rows: unknown[][];
  done: boolean;
  remaining: number;
}

const HISTORY_KEY = 'unidb-studio.sqlHistory';
const HISTORY_MAX = 20;
const SAVED_KEY = 'unidb-studio.savedQueries';

function loadHistory(): string[] {
  try {
    const raw = localStorage.getItem(HISTORY_KEY);
    const arr = raw ? JSON.parse(raw) : [];
    return Array.isArray(arr) ? arr.slice(0, HISTORY_MAX) : [];
  } catch {
    return [];
  }
}

function loadSaved(): string[] {
  try {
    const arr = JSON.parse(localStorage.getItem(SAVED_KEY) ?? '[]');
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

const EXAMPLES = [
  { label: 'Select rows', sql: 'SELECT * FROM <table> LIMIT 50;' },
  { label: 'Filter (param)', sql: 'SELECT * FROM <table> WHERE id = $1;' },
  { label: 'Aggregate', sql: 'SELECT status, COUNT(*) FROM <table> GROUP BY status;' },
  { label: 'Join', sql: 'SELECT a.*, b.name\nFROM <table> a\nJOIN <other> b ON b.id = a.<other>_id;' },
  { label: 'Vector search (NEAR)', sql: 'SELECT * FROM <table>\nWHERE NEAR(<vector_col>, [0.1, 0.2, 0.3, 0.4], 5);' },
  { label: 'Create vector index', sql: 'CREATE INDEX idx_<table>_<col> ON <table> USING HNSW (<col>);' },
  { label: 'Explain analyze', sql: 'EXPLAIN ANALYZE SELECT * FROM <table> WHERE id = $1;' },
];

const INDENT = '  ';
const fmt = (ms: number | null) => (ms == null ? '—' : `${ms.toFixed(2)} ms`);
const preview = (q: string) => q.replace(/\s+/g, ' ').trim().slice(0, 80);

export function SqlEditor({
  sql,
  onSqlChange,
  paramsText,
  onParamsTextChange,
}: {
  sql: string;
  onSqlChange: (s: string) => void;
  paramsText: string;
  onParamsTextChange: (s: string) => void;
}) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<CatalogError | null>(null);
  const [results, setResults] = useState<DataGridResult[] | null>(null);
  const [roundTripMs, setRoundTripMs] = useState<number | null>(null);
  const [serverMs, setServerMs] = useState<number | null>(null);
  const [ranSelect, setRanSelect] = useState(false);
  const [planLines, setPlanLines] = useState<string[] | null>(null);

  // ---- transaction session ------------------------------------------------
  const [session, setSession] = useState<Session | null>(null);
  const [isoChoice, setIsoChoice] = useState('read_committed');
  const [sessionMsg, setSessionMsg] = useState<string | null>(null);

  async function startSession() {
    setError(null);
    setSessionMsg(null);
    try {
      const s = await txnBegin(isoChoice);
      setSession({ txnId: s.txnId, isolation: s.isolation });
      setSessionMsg(`Session #${s.txnId} started (${s.isolation}). DDL must run outside a session.`);
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
    }
  }
  async function endSession(commit: boolean) {
    if (!session) return;
    const id = session.txnId;
    try {
      const r = commit ? await txnCommit(id) : await txnRollback(id);
      setSessionMsg(`Session #${id} ${r.state}.`);
    } catch (e: any) {
      setSessionMsg(`Session #${id} ${commit ? 'commit' : 'rollback'} failed: ${e?.message}`);
    } finally {
      setSession(null);
    }
  }

  // ---- query history (persisted) ------------------------------------------
  const [history, setHistory] = useState<string[]>(loadHistory);
  const [showHistory, setShowHistory] = useState(false);
  const [showSaved, setShowSaved] = useState(false);
  const [showExamples, setShowExamples] = useState(false);

  function pushHistory(q: string) {
    const trimmed = q.trim();
    if (!trimmed) return;
    const next = [trimmed, ...history.filter((h) => h !== trimmed)].slice(0, HISTORY_MAX);
    setHistory(next);
    try {
      localStorage.setItem(HISTORY_KEY, JSON.stringify(next));
    } catch {
      /* storage full / unavailable — history is best-effort */
    }
  }
  function recall(q: string) {
    onSqlChange(q);
    setShowHistory(false);
    textareaRef.current?.focus();
  }
  function clearHistory() {
    setHistory([]);
    try {
      localStorage.removeItem(HISTORY_KEY);
    } catch {
      /* ignore */
    }
  }

  // ---- vector embed helper --------------------------------------------------
  const [showEmbed, setShowEmbed] = useState(false);
  const [embedText, setEmbedText] = useState('');
  const [embedCopied, setEmbedCopied] = useState(false);
  const embedVec = useMemo(() => (embedText.trim() ? embed(embedText) : null), [embedText]);

  async function copyVector() {
    if (!embedVec) return;
    await navigator.clipboard.writeText(vectorToSql(embedVec));
    setEmbedCopied(true);
    setTimeout(() => setEmbedCopied(false), 1200);
  }
  function insertVector() {
    const el = textareaRef.current;
    if (!embedVec || !el) return;
    const vecStr = vectorToSql(embedVec);
    const start = el.selectionStart ?? sql.length;
    const end = el.selectionEnd ?? sql.length;
    const next = sql.slice(0, start) + vecStr + sql.slice(end);
    flushSync(() => onSqlChange(next));
    el.selectionStart = el.selectionEnd = start + vecStr.length;
    el.focus();
  }

  // ---- saved queries (pinned, persisted) ------------------------------------
  const [saved, setSaved] = useState<string[]>(loadSaved);
  function persistSaved(next: string[]) {
    setSaved(next);
    try {
      localStorage.setItem(SAVED_KEY, JSON.stringify(next));
    } catch {
      /* best-effort */
    }
  }
  function saveCurrent() {
    const q = sql.trim();
    if (!q || saved.includes(q)) return;
    persistSaved([q, ...saved].slice(0, 50));
  }
  function unsave(q: string) {
    persistSaved(saved.filter((s) => s !== q));
  }
  function recallSaved(q: string) {
    onSqlChange(q);
    setShowSaved(false);
    textareaRef.current?.focus();
  }
  const isSaved = saved.includes(sql.trim());

  function useExample(s: string) {
    onSqlChange(s);
    setShowExamples(false);
    textareaRef.current?.focus();
  }

  function parseParams(): unknown[] {
    const t = paramsText.trim();
    if (!t) return [];
    const parsed = JSON.parse(t);
    if (!Array.isArray(parsed)) throw new Error('params must be a JSON array');
    return parsed;
  }

  // ---- cursor streaming -----------------------------------------------------
  const [stream, setStream] = useState<StreamState | null>(null);

  async function stopStream(current = stream) {
    if (current && !current.done) await cursorClose(current.cursorId);
    setStream(null);
  }

  async function loadMore(current: StreamState) {
    setLoading(true);
    try {
      const p = await cursorPage(current.cursorId, 200);
      setStream({
        ...current,
        columns: p.columns.length ? p.columns : current.columns,
        rows: [...current.rows, ...p.rows],
        done: p.done,
        remaining: p.remaining,
      });
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
      setStream(null);
    } finally {
      setLoading(false);
    }
  }

  async function startStream() {
    setError(null);
    setResults(null);
    setPlanLines(null);
    setStream(null);
    let params: unknown[];
    try {
      params = parseParams();
    } catch (e: any) {
      setError({ code: 'BAD_PARAMS', message: `params: ${e.message}`, status: 0 });
      return;
    }
    setLoading(true);
    try {
      const c = await runSqlCursor(sql, params);
      const initial: StreamState = { cursorId: c.cursorId, columns: c.columns, rows: [], done: false, remaining: c.rowCount ?? 0 };
      setStream(initial);
      setLoading(false);
      await loadMore(initial);
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
      setStream(null);
      setLoading(false);
    }
  }

  async function runExplain() {
    setError(null);
    setResults(null);
    setPlanLines(null);
    let params: unknown[];
    try {
      params = parseParams();
    } catch (e: any) {
      setError({ code: 'BAD_PARAMS', message: `params: ${e.message}`, status: 0 });
      return;
    }
    setLoading(true);
    try {
      setPlanLines(await explain(sql, params));
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
    } finally {
      setLoading(false);
    }
  }

  async function run() {
    setLoading(true);
    setError(null);
    setResults(null);
    setRoundTripMs(null);
    setServerMs(null);
    setRanSelect(false);
    setPlanLines(null);
    setStream(null);

    let params: unknown[];
    try {
      params = parseParams();
    } catch (e: any) {
      setError({ code: 'BAD_PARAMS', message: `params: ${e.message}`, status: 0 });
      setLoading(false);
      return;
    }

    try {
      const out = await runSql(sql, params, { txnId: (session?.txnId ?? null) as any });
      setResults(out.results);
      setRoundTripMs(out.roundTripMs);
      pushHistory(sql);

      // Server-exec timing is meaningful only for a single read query, and is
      // gathered by a COMPANION EXPLAIN ANALYZE call — never conflated with the
      // round-trip above. Failure here is non-fatal (query already succeeded).
      if (isSingleSelect(sql)) {
        setRanSelect(true);
        try {
          const ea = await explainAnalyze(sql, params);
          setServerMs(ea.serverMs);
        } catch {
          setServerMs(null);
        }
      }
    } catch (e: any) {
      setError({ code: e?.code, message: e?.message ?? String(e), status: e?.status });
      // A failed mutating statement aborts + destroys the session server-side
      // (Postgres-without-savepoints); reflect that so the UI doesn't keep
      // sending a dead X-Txn-Id. Pure-read failures leave the session open.
      if (session && (e?.code === 'TXN_NOT_FOUND' || !isSingleSelect(sql))) {
        setSessionMsg(`Session #${session.txnId} aborted by the failed statement — re-begin to continue.`);
        setSession(null);
      }
    } finally {
      setLoading(false);
    }
  }

  function clearEditor() {
    onSqlChange('');
    onParamsTextChange('');
    setResults(null);
    setError(null);
    setRoundTripMs(null);
    setServerMs(null);
    setRanSelect(false);
    setPlanLines(null);
    stopStream();
    textareaRef.current?.focus();
  }

  function onKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
      e.preventDefault();
      if (!loading) run();
      return;
    }
    if (e.key === 'Tab') {
      e.preventDefault();
      indentSelection(e.shiftKey);
    }
  }

  // Insert/remove two spaces at the caret (or across selected lines). Caret is
  // restored synchronously via flushSync so it lands correctly on the updated
  // textarea value (mirrors v1's `await tick()`).
  function indentSelection(outdent: boolean) {
    const el = textareaRef.current;
    if (!el) return;
    const { selectionStart: start, selectionEnd: end, value } = el;
    const lineStart = value.lastIndexOf('\n', start - 1) + 1;
    const multiline = value.slice(lineStart, end).includes('\n') || start !== end;

    let selStart: number;
    let selEnd: number;
    let next: string;
    if (multiline) {
      const lines = value.slice(lineStart, end).split('\n');
      const block = lines.map((ln) => (outdent ? ln.replace(/^ {1,2}/, '') : INDENT + ln)).join('\n');
      next = value.slice(0, lineStart) + block + value.slice(end);
      selStart = lineStart;
      selEnd = lineStart + block.length;
    } else if (outdent) {
      const removed = value.slice(lineStart, start).match(/ {1,2}$/)?.[0].length ?? 0;
      next = value.slice(0, start - removed) + value.slice(start);
      selStart = selEnd = start - removed;
    } else {
      next = value.slice(0, start) + INDENT + value.slice(end);
      selStart = selEnd = start + INDENT.length;
    }

    flushSync(() => onSqlChange(next));
    el.selectionStart = selStart;
    el.selectionEnd = selEnd;
  }

  return (
    <div className="flex flex-col gap-3">
      {/* Session bar */}
      <div className="flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm">
        {session ? (
          <>
            <span className="font-semibold text-brand">● session #{session.txnId}</span>
            <span className="font-mono text-xs text-text-light">{session.isolation}</span>
            <span className="flex-1" />
            <button
              className="h-[26px] rounded-md border border-transparent bg-brand px-3 text-sm text-brand-text-on disabled:opacity-45"
              onClick={() => endSession(true)}
              disabled={loading}
            >
              Commit
            </button>
            <button
              className="h-[26px] rounded-md border border-border bg-secondary px-3 text-sm hover:border-error hover:text-error disabled:opacity-45"
              onClick={() => endSession(false)}
              disabled={loading}
            >
              Rollback
            </button>
          </>
        ) : (
          <>
            <span className="text-text-light">Auto-commit</span>
            <select
              className="h-8 rounded-md border border-border bg-secondary px-2 text-sm"
              value={isoChoice}
              onChange={(e) => setIsoChoice(e.target.value)}
              title="Isolation level for the session"
            >
              <option value="read_committed">read committed</option>
              <option value="repeatable_read">repeatable read</option>
              <option value="serializable">serializable</option>
            </select>
            <span className="flex-1" />
            <button
              className="h-[26px] rounded-md border border-border bg-secondary px-3 text-sm hover:border-border-strong disabled:opacity-45"
              onClick={startSession}
              disabled={loading}
            >
              Begin session
            </button>
          </>
        )}
      </div>
      {sessionMsg && <p className="m-0 text-sm text-text-light">{sessionMsg}</p>}

      {/* Toolbar */}
      <div className="flex gap-2">
        <div className="relative">
          <button
            className="h-[26px] rounded-md border border-border bg-secondary px-2 text-sm hover:border-border-strong disabled:opacity-45"
            onClick={() => {
              setShowHistory((v) => !v);
              setShowExamples(false);
              setShowSaved(false);
            }}
            disabled={history.length === 0}
            title="Recent queries"
          >
            History ▾
          </button>
          {showHistory && (
            <div
              className="absolute top-[calc(100%+4px)] left-0 z-50 max-h-80 min-w-[260px] overflow-auto rounded-lg border border-border bg-card p-1 shadow-[var(--shadow-overlay)]"
              onMouseLeave={() => setShowHistory(false)}
            >
              {history.map((h, i) => (
                <button
                  key={i}
                  className="block w-full truncate rounded-md px-2 py-2 text-left font-mono text-sm hover:bg-accent"
                  onClick={() => recall(h)}
                  title={h}
                >
                  {preview(h)}
                </button>
              ))}
              <div className="mt-1 border-t border-border-muted pt-1 text-right">
                <button className="text-xs text-text-muted hover:text-error" onClick={clearHistory}>
                  Clear history
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="relative">
          <button
            className="h-[26px] rounded-md border border-border bg-secondary px-2 text-sm hover:border-border-strong disabled:opacity-45"
            onClick={() => {
              setShowSaved((v) => !v);
              setShowHistory(false);
              setShowExamples(false);
            }}
            disabled={saved.length === 0}
            title="Saved queries"
          >
            Saved ▾
          </button>
          {showSaved && (
            <div
              className="absolute top-[calc(100%+4px)] left-0 z-50 max-h-80 min-w-[260px] overflow-auto rounded-lg border border-border bg-card p-1 shadow-[var(--shadow-overlay)]"
              onMouseLeave={() => setShowSaved(false)}
            >
              {saved.map((q) => (
                <div key={q} className="flex items-center">
                  <button
                    className="flex-1 truncate rounded-md px-2 py-2 text-left font-mono text-sm hover:bg-accent"
                    onClick={() => recallSaved(q)}
                    title={q}
                  >
                    {preview(q)}
                  </button>
                  <button className="px-2 py-1 text-xs text-text-muted hover:text-error" title="Remove" onClick={() => unsave(q)}>
                    ✕
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>

        <button
          className="h-[26px] rounded-md border border-border bg-secondary px-2 text-sm hover:border-border-strong disabled:opacity-45"
          onClick={saveCurrent}
          disabled={!sql.trim() || isSaved}
          title="Pin this query"
        >
          {isSaved ? '★ Saved' : '☆ Save'}
        </button>

        <div className="relative">
          <button
            className="h-[26px] rounded-md border border-border bg-secondary px-2 text-sm hover:border-border-strong"
            onClick={() => {
              setShowExamples((v) => !v);
              setShowHistory(false);
              setShowSaved(false);
            }}
            title="Insert an example query"
          >
            Examples ▾
          </button>
          {showExamples && (
            <div
              className="absolute top-[calc(100%+4px)] left-0 z-50 max-h-80 min-w-[260px] overflow-auto rounded-lg border border-border bg-card p-1 shadow-[var(--shadow-overlay)]"
              onMouseLeave={() => setShowExamples(false)}
            >
              {EXAMPLES.map((ex) => (
                <button
                  key={ex.label}
                  className="block w-full truncate rounded-md px-2 py-2 text-left text-sm hover:bg-accent"
                  onClick={() => useExample(ex.sql)}
                >
                  {ex.label}
                </button>
              ))}
            </div>
          )}
        </div>

        <button
          className={cn(
            'h-[26px] rounded-md border border-border bg-secondary px-2 text-sm hover:border-border-strong',
            showEmbed && 'border-brand text-brand',
          )}
          onClick={() => {
            setShowEmbed((v) => !v);
            setShowHistory(false);
            setShowExamples(false);
            setShowSaved(false);
          }}
          title="Generate a NEAR() vector from plain text"
        >
          Embed
        </button>
      </div>

      {/* Embed panel */}
      {showEmbed && (
        <div className="flex flex-wrap items-center gap-2 rounded-md border border-border bg-card px-3 py-2">
          <input
            className="h-7 min-w-[180px] flex-1 rounded-md border border-border bg-secondary px-2 font-mono text-sm outline-none focus-visible:border-border-strong focus-visible:ring-[2px] focus-visible:ring-ring/40"
            value={embedText}
            onChange={(e) => setEmbedText(e.target.value)}
            placeholder="Type text to embed — e.g. wireless headphones noise cancellation…"
            spellCheck={false}
          />
          {embedVec ? (
            (() => {
              const nonZero = embedVec.filter((v: number) => v > 0).length;
              return (
                <>
                  <div className="flex min-w-0 flex-1 items-center gap-1.5">
                    <span
                      className={cn('text-xs font-semibold whitespace-nowrap', nonZero <= 2 ? 'text-warn' : 'text-brand')}
                      title="More non-zero dimensions = better discrimination between results"
                    >
                      {nonZero} dim{nonZero === 1 ? '' : 's'} active
                      {nonZero <= 2 ? ' ⚠ add more words for better results' : ''}
                    </span>
                    <code className="min-w-0 flex-1 truncate text-xs text-text-muted">
                      [{embedVec.slice(0, 6).map((v: number) => v.toFixed(2)).join(', ')}, …]
                    </code>
                    <button
                      className="h-6 rounded-md border border-border px-2 text-xs whitespace-nowrap hover:border-border-strong hover:text-brand"
                      onClick={copyVector}
                    >
                      {embedCopied ? '✓ Copied' : 'Copy'}
                    </button>
                    <button
                      className="h-6 rounded-md border border-brand bg-brand px-2 text-xs whitespace-nowrap text-brand-text-on hover:bg-brand-hover"
                      onClick={insertVector}
                      title="Insert vector at cursor position in the editor"
                    >
                      Insert
                    </button>
                  </div>
                  <div className="w-full text-xs text-text-muted">
                    {nonZero <= 2 ? (
                      'Use more descriptive words to activate more dimensions and improve match accuracy.'
                    ) : (
                      <>
                        Ready — click Insert. Add <code className="text-foreground">vec_distance</code> to SELECT to see match scores
                        (below 1.3 = relevant, above = noise). Never put it in WHERE — the engine only exposes it in SELECT. Use 5+
                        words for tighter distances.
                      </>
                    )}
                  </div>
                </>
              );
            })()
          ) : (
            <span className="text-xs text-text-muted">
              word-hash → 64-dim vector · more words = better results · matches demo/vector_demo.py
            </span>
          )}
        </div>
      )}

      <textarea
        ref={textareaRef}
        value={sql}
        onChange={(e) => onSqlChange(e.target.value)}
        onKeyDown={onKeyDown}
        spellCheck={false}
        placeholder="SELECT * FROM ..."
        rows={6}
        className="w-full resize-y rounded-lg border border-border bg-card px-3 py-2.5 font-mono text-md leading-normal outline-none focus-visible:border-border-strong focus-visible:ring-[2px] focus-visible:ring-ring/40"
        style={{ tabSize: 2 }}
      />

      <div className="flex items-center gap-3">
        <button
          className="h-8 rounded-md bg-brand px-3 text-md font-medium text-brand-text-on hover:bg-brand-hover disabled:opacity-45"
          onClick={run}
          disabled={loading}
        >
          {loading ? 'Running…' : 'Run'}
        </button>
        <button
          className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong disabled:opacity-45"
          onClick={runExplain}
          disabled={loading || !sql.trim()}
        >
          Explain
        </button>
        <button
          className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong disabled:opacity-45"
          onClick={startStream}
          disabled={loading || !isSingleSelect(sql)}
          title="Page a large read server-side via a cursor"
        >
          Stream
        </button>
        <button
          className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong disabled:opacity-45"
          onClick={clearEditor}
          disabled={loading || (!sql && !paramsText)}
        >
          Clear
        </button>
        <span className="text-sm text-text-muted">⌘/Ctrl + Enter · Tab to indent</span>
        <input
          className="h-8 flex-1 rounded-md border border-border bg-secondary px-3 font-mono text-sm outline-none focus-visible:border-border-strong focus-visible:ring-[2px] focus-visible:ring-ring/40"
          value={paramsText}
          onChange={(e) => onParamsTextChange(e.target.value)}
          placeholder='params (JSON array, e.g. [1, "alice"])'
          spellCheck={false}
        />
      </div>

      {roundTripMs != null && (
        <div className="flex gap-5 text-sm">
          <span className="font-mono text-text-light">
            round-trip: <b className="text-foreground">{fmt(roundTripMs)}</b>
          </span>
          {ranSelect && (
            <span className="font-mono text-text-light">
              server exec: <b className="text-foreground">{serverMs == null ? 'n/a' : fmt(serverMs)}</b>{' '}
              <span className="text-text-muted">(EXPLAIN ANALYZE)</span>
            </span>
          )}
        </div>
      )}

      <ErrorBox error={error} />

      {planLines && (
        <div className="overflow-hidden rounded-lg border border-border bg-card">
          <div className="border-b border-border px-3 py-1.5 text-sm font-semibold">
            Query plan <span className="font-normal text-text-muted">(EXPLAIN)</span>
          </div>
          <pre className="m-0 overflow-auto p-3 font-mono text-sm leading-normal">{planLines.join('\n')}</pre>
        </div>
      )}

      {stream && (
        <>
          <div className="mb-1.5 flex items-center gap-2">
            <span className="font-mono text-sm text-text-light">
              streaming · {stream.rows.length} rows loaded{stream.done ? ' · done' : ` · ~${stream.remaining} remaining`}
            </span>
            <span className="flex-1" />
            {!stream.done && (
              <button
                className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong disabled:opacity-45"
                onClick={() => loadMore(stream)}
                disabled={loading}
              >
                Load more
              </button>
            )}
            <button
              className="h-8 rounded-md border border-border bg-secondary px-3 text-md hover:border-border-strong"
              onClick={() => stopStream()}
            >
              Close
            </button>
          </div>
          <DataGrid result={{ type: 'rows', columns: stream.columns, rows: stream.rows }} />
        </>
      )}

      {results &&
        results.map((result, i) => (
          <div key={i}>
            {results.length > 1 && <p className="mt-2 mb-0.5 text-sm font-semibold text-text-light">statement {i + 1}</p>}
            <DataGrid result={result} />
          </div>
        ))}
    </div>
  );
}

// src-v1/lib/SqlEditor.svelte
<script>
  import { tick } from 'svelte';
  import {
    runSql, explain, explainAnalyze, isSingleSelect,
    txnBegin, txnCommit, txnRollback,
    runSqlCursor, cursorPage, cursorClose,
  } from './api.js';
  import { embed, vectorToSql } from './embed.js';
  import ResultsGrid from './ResultsGrid.svelte';
  import ErrorBox from './ErrorBox.svelte';

  // `sql` may be seeded from outside (e.g. clicking a table). Bindable so the
  // parent can push a new query in.
  let { sql = $bindable('SELECT 1;'), paramsText = $bindable('') } = $props();

  let loading = $state(false);
  let error = $state(null);
  let results = $state(null);
  let roundTripMs = $state(null);
  let serverMs = $state(null); // null = not applicable (non-SELECT)
  let ranSelect = $state(false);
  let planLines = $state(null); // EXPLAIN plan (array of strings) | null

  // ---- transaction session ------------------------------------------------
  let session = $state(null); // { txnId, isolation } | null
  let isoChoice = $state('read_committed');
  let sessionMsg = $state(null);

  async function startSession() {
    error = null;
    sessionMsg = null;
    try {
      const s = await txnBegin(isoChoice);
      session = { txnId: s.txnId, isolation: s.isolation };
      sessionMsg = `Session #${s.txnId} started (${s.isolation}). DDL must run outside a session.`;
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
    }
  }
  async function endSession(commit) {
    if (!session) return;
    const id = session.txnId;
    try {
      const r = commit ? await txnCommit(id) : await txnRollback(id);
      sessionMsg = `Session #${id} ${r.state}.`;
    } catch (e) {
      sessionMsg = `Session #${id} ${commit ? 'commit' : 'rollback'} failed: ${e.message}`;
    } finally {
      session = null;
    }
  }

  let textarea; // bound element — needed for Tab-to-indent caret handling

  // ---- query history (persisted) ------------------------------------------
  const HISTORY_KEY = 'unidb-studio.sqlHistory';
  const HISTORY_MAX = 20;
  let history = $state(loadHistory());
  let showHistory = $state(false);
  let showExamples = $state(false);

  // ---- vector embed helper ------------------------------------------------
  let showEmbed = $state(false);
  let embedText = $state('');
  let embedCopied = $state(false);
  const embedVec = $derived(embedText.trim() ? embed(embedText) : null);

  async function copyVector() {
    if (!embedVec) return;
    await navigator.clipboard.writeText(vectorToSql(embedVec));
    embedCopied = true;
    setTimeout(() => (embedCopied = false), 1200);
  }

  async function insertVector() {
    if (!embedVec || !textarea) return;
    const vecStr = vectorToSql(embedVec);
    const start = textarea.selectionStart ?? sql.length;
    const end   = textarea.selectionEnd   ?? sql.length;
    sql = sql.slice(0, start) + vecStr + sql.slice(end);
    await tick();
    textarea.selectionStart = textarea.selectionEnd = start + vecStr.length;
    textarea.focus();
  }

  // ---- saved queries (pinned, persisted) ----------------------------------
  const SAVED_KEY = 'unidb-studio.savedQueries';
  let saved = $state(loadSaved());
  let showSaved = $state(false);

  function loadSaved() {
    try {
      const arr = JSON.parse(localStorage.getItem(SAVED_KEY) ?? '[]');
      return Array.isArray(arr) ? arr : [];
    } catch {
      return [];
    }
  }
  function persistSaved() {
    try {
      localStorage.setItem(SAVED_KEY, JSON.stringify(saved));
    } catch {
      /* best-effort */
    }
  }
  function saveCurrent() {
    const q = sql.trim();
    if (!q || saved.includes(q)) return;
    saved = [q, ...saved].slice(0, 50);
    persistSaved();
  }
  function unsave(q) {
    saved = saved.filter((s) => s !== q);
    persistSaved();
  }
  function recallSaved(q) {
    sql = q;
    showSaved = false;
    textarea?.focus();
  }
  const isSaved = $derived(saved.includes(sql.trim()));

  function loadHistory() {
    try {
      const raw = localStorage.getItem(HISTORY_KEY);
      const arr = raw ? JSON.parse(raw) : [];
      return Array.isArray(arr) ? arr.slice(0, HISTORY_MAX) : [];
    } catch {
      return [];
    }
  }
  function pushHistory(q) {
    const trimmed = q.trim();
    if (!trimmed) return;
    // De-dupe: drop any existing identical entry, put this one on top.
    const next = [trimmed, ...history.filter((h) => h !== trimmed)].slice(0, HISTORY_MAX);
    history = next;
    try {
      localStorage.setItem(HISTORY_KEY, JSON.stringify(next));
    } catch {
      /* storage full / unavailable — history is best-effort */
    }
  }
  function recall(q) {
    sql = q;
    showHistory = false;
    textarea?.focus();
  }
  function clearHistory() {
    history = [];
    try {
      localStorage.removeItem(HISTORY_KEY);
    } catch {
      /* ignore */
    }
  }

  // ---- example snippets ----------------------------------------------------
  const EXAMPLES = [
    { label: 'Select rows', sql: 'SELECT * FROM <table> LIMIT 50;' },
    { label: 'Filter (param)', sql: 'SELECT * FROM <table> WHERE id = $1;' },
    { label: 'Aggregate', sql: 'SELECT status, COUNT(*) FROM <table> GROUP BY status;' },
    { label: 'Join', sql: 'SELECT a.*, b.name\nFROM <table> a\nJOIN <other> b ON b.id = a.<other>_id;' },
    { label: 'Vector search (NEAR)', sql: 'SELECT * FROM <table>\nWHERE NEAR(<vector_col>, [0.1, 0.2, 0.3, 0.4], 5);' },
    { label: 'Create vector index', sql: 'CREATE INDEX idx_<table>_<col> ON <table> USING HNSW (<col>);' },
    { label: 'Explain analyze', sql: 'EXPLAIN ANALYZE SELECT * FROM <table> WHERE id = $1;' },
  ];
  function useExample(s) {
    sql = s;
    showExamples = false;
    textarea?.focus();
  }

  function clearEditor() {
    sql = '';
    paramsText = '';
    results = null;
    error = null;
    roundTripMs = null;
    serverMs = null;
    ranSelect = false;
    planLines = null;
    stopStream();
    textarea?.focus();
  }

  // ---- cursor streaming ---------------------------------------------------
  let stream = $state(null); // { cursorId, columns, rows, done, remaining } | null

  async function startStream() {
    error = null;
    results = null;
    planLines = null;
    stream = null;
    let params;
    try {
      params = parseParams();
    } catch (e) {
      error = { code: 'BAD_PARAMS', message: `params: ${e.message}`, status: 0 };
      return;
    }
    loading = true;
    try {
      const c = await runSqlCursor(sql, params);
      stream = { cursorId: c.cursorId, columns: c.columns, rows: [], done: false, remaining: c.rowCount ?? 0 };
      await loadMore();
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
      stream = null;
    } finally {
      loading = false;
    }
  }
  async function loadMore() {
    if (!stream || stream.done) return;
    loading = true;
    try {
      const p = await cursorPage(stream.cursorId, 200);
      stream = {
        ...stream,
        columns: p.columns.length ? p.columns : stream.columns,
        rows: [...stream.rows, ...p.rows],
        done: p.done,
        remaining: p.remaining,
      };
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
      stream = null;
    } finally {
      loading = false;
    }
  }
  async function stopStream() {
    if (stream && !stream.done) await cursorClose(stream.cursorId);
    stream = null;
  }

  async function runExplain() {
    error = null;
    results = null;
    planLines = null;
    let params;
    try {
      params = parseParams();
    } catch (e) {
      error = { code: 'BAD_PARAMS', message: `params: ${e.message}`, status: 0 };
      return;
    }
    loading = true;
    try {
      planLines = await explain(sql, params);
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
    } finally {
      loading = false;
    }
  }

  function parseParams() {
    const t = paramsText.trim();
    if (!t) return [];
    const parsed = JSON.parse(t); // may throw -> caught in run()
    if (!Array.isArray(parsed)) throw new Error('params must be a JSON array');
    return parsed;
  }

  async function run() {
    loading = true;
    error = null;
    results = null;
    roundTripMs = null;
    serverMs = null;
    ranSelect = false;
    planLines = null;
    stream = null;

    let params;
    try {
      params = parseParams();
    } catch (e) {
      error = { code: 'BAD_PARAMS', message: `params: ${e.message}`, status: 0 };
      loading = false;
      return;
    }

    try {
      const out = await runSql(sql, params, { txnId: session?.txnId });
      results = out.results;
      roundTripMs = out.roundTripMs;
      pushHistory(sql);

      // Server-exec timing is meaningful only for a single read query, and is
      // gathered by a COMPANION EXPLAIN ANALYZE call — never conflated with the
      // round-trip above. Failure here is non-fatal (query already succeeded).
      if (isSingleSelect(sql)) {
        ranSelect = true;
        try {
          const ea = await explainAnalyze(sql, params);
          serverMs = ea.serverMs;
        } catch {
          serverMs = null;
        }
      }
    } catch (e) {
      error = { code: e.code, message: e.message, status: e.status };
      // A failed mutating statement aborts + destroys the session server-side
      // (Postgres-without-savepoints); reflect that so the UI doesn't keep
      // sending a dead X-Txn-Id. Pure-read failures leave the session open.
      if (session && (e.code === 'TXN_NOT_FOUND' || !isSingleSelect(sql))) {
        sessionMsg = `Session #${session.txnId} aborted by the failed statement — re-begin to continue.`;
        session = null;
      }
    } finally {
      loading = false;
    }
  }

  function onKeydown(e) {
    // Cmd/Ctrl+Enter to run.
    if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
      e.preventDefault();
      if (!loading) run();
      return;
    }
    // Tab / Shift+Tab indent instead of moving focus out of the editor.
    if (e.key === 'Tab') {
      e.preventDefault();
      indentSelection(e.shiftKey);
    }
  }

  // Insert/remove two spaces at the caret (or across selected lines). Caret is
  // restored after `tick()` so it lands correctly once Svelte flushes the new
  // textarea value.
  const INDENT = '  ';
  async function indentSelection(outdent) {
    const el = textarea;
    if (!el) return;
    const { selectionStart: start, selectionEnd: end, value } = el;
    const lineStart = value.lastIndexOf('\n', start - 1) + 1;
    const multiline = value.slice(lineStart, end).includes('\n') || start !== end;

    let selStart;
    let selEnd;
    if (multiline) {
      const lines = value.slice(lineStart, end).split('\n');
      const block = lines.map((ln) => (outdent ? ln.replace(/^ {1,2}/, '') : INDENT + ln)).join('\n');
      sql = value.slice(0, lineStart) + block + value.slice(end);
      selStart = lineStart;
      selEnd = lineStart + block.length;
    } else if (outdent) {
      const removed = value.slice(lineStart, start).match(/ {1,2}$/)?.[0].length ?? 0;
      sql = value.slice(0, start - removed) + value.slice(start);
      selStart = selEnd = start - removed;
    } else {
      sql = value.slice(0, start) + INDENT + value.slice(end);
      selStart = selEnd = start + INDENT.length;
    }

    await tick();
    el.selectionStart = selStart;
    el.selectionEnd = selEnd;
  }

  const fmt = (ms) => (ms == null ? '—' : `${ms.toFixed(2)} ms`);
  const preview = (q) => q.replace(/\s+/g, ' ').trim().slice(0, 80);
</script>

<div class="editor">
  <div class="session-bar">
    {#if session}
      <span class="sess-on">● session #{session.txnId}</span>
      <span class="sess-iso">{session.isolation}</span>
      <span class="grow"></span>
      <button class="sess-commit" onclick={() => endSession(true)} disabled={loading}>Commit</button>
      <button class="sess-rollback" onclick={() => endSession(false)} disabled={loading}>Rollback</button>
    {:else}
      <span class="sess-off">Auto-commit</span>
      <select class="iso" bind:value={isoChoice} title="Isolation level for the session">
        <option value="read_committed">read committed</option>
        <option value="repeatable_read">repeatable read</option>
        <option value="serializable">serializable</option>
      </select>
      <span class="grow"></span>
      <button class="sess-begin" onclick={startSession} disabled={loading}>Begin session</button>
    {/if}
  </div>
  {#if sessionMsg}<p class="sess-msg">{sessionMsg}</p>{/if}

  <div class="editor-tools">
    <div class="menu-wrap">
      <button
        class="tool"
        onclick={() => { showHistory = !showHistory; showExamples = false; showSaved = false; }}
        disabled={history.length === 0}
        title="Recent queries"
      >History ▾</button>
      {#if showHistory}
        <div class="dropdown" role="presentation" onmouseleave={() => (showHistory = false)}>
          {#each history as h}
            <button class="drop-item" onclick={() => recall(h)} title={h}>{preview(h)}</button>
          {/each}
          <div class="drop-foot">
            <button class="linkbtn" onclick={clearHistory}>Clear history</button>
          </div>
        </div>
      {/if}
    </div>

    <div class="menu-wrap">
      <button
        class="tool"
        onclick={() => { showSaved = !showSaved; showHistory = false; showExamples = false; }}
        disabled={saved.length === 0}
        title="Saved queries"
      >Saved ▾</button>
      {#if showSaved}
        <div class="dropdown" role="presentation" onmouseleave={() => (showSaved = false)}>
          {#each saved as q}
            <div class="drop-line">
              <button class="drop-item" onclick={() => recallSaved(q)} title={q}>{preview(q)}</button>
              <button class="drop-x" title="Remove" onclick={() => unsave(q)}>✕</button>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    <button class="tool" onclick={saveCurrent} disabled={!sql.trim() || isSaved} title="Pin this query">
      {isSaved ? '★ Saved' : '☆ Save'}
    </button>

    <div class="menu-wrap">
      <button
        class="tool"
        onclick={() => { showExamples = !showExamples; showHistory = false; showSaved = false; }}
        title="Insert an example query"
      >Examples ▾</button>
      {#if showExamples}
        <div class="dropdown" role="presentation" onmouseleave={() => (showExamples = false)}>
          {#each EXAMPLES as ex}
            <button class="drop-item" onclick={() => useExample(ex.sql)}>{ex.label}</button>
          {/each}
        </div>
      {/if}
    </div>

    <button
      class="tool"
      class:embed-active={showEmbed}
      onclick={() => { showEmbed = !showEmbed; showHistory = false; showExamples = false; showSaved = false; }}
      title="Generate a NEAR() vector from plain text"
    >Embed</button>
  </div>

  {#if showEmbed}
    <div class="embed-panel">
      <input
        class="embed-input"
        bind:value={embedText}
        placeholder="Type text to embed — e.g. wireless headphones noise cancellation…"
        spellcheck="false"
      />
      {#if embedVec}
        {@const nonZero = embedVec.filter(v => v > 0).length}
        <div class="embed-out">
          <span class="embed-dims" class:embed-dims-warn={nonZero <= 2} title="More non-zero dimensions = better discrimination between results">
            {nonZero} dim{nonZero === 1 ? '' : 's'} active
            {#if nonZero <= 2}⚠ add more words for better results{/if}
          </span>
          <code class="embed-preview">[{embedVec.slice(0, 6).map(v => v.toFixed(2)).join(', ')}, …]</code>
          <button class="embed-btn" onclick={copyVector}>{embedCopied ? '✓ Copied' : 'Copy'}</button>
          <button class="embed-btn primary" onclick={insertVector} title="Insert vector at cursor position in the editor">Insert</button>
        </div>
        <div class="embed-tip">
          {#if nonZero <= 2}Use more descriptive words to activate more dimensions and improve match accuracy.{:else}Ready — click Insert. Add <code>vec_distance</code> to SELECT to see match scores (below 1.3 = relevant, above = noise). Never put it in WHERE — the engine only exposes it in SELECT. Use 5+ words for tighter distances.{/if}
        </div>
      {:else}
        <span class="embed-hint">word-hash → 64-dim vector · more words = better results · matches demo/vector_demo.py</span>
      {/if}
    </div>
  {/if}

  <textarea
    bind:this={textarea}
    bind:value={sql}
    onkeydown={onKeydown}
    spellcheck="false"
    placeholder="SELECT * FROM ..."
    rows="6"
  ></textarea>

  <div class="controls">
    <button onclick={run} disabled={loading}>
      {loading ? 'Running…' : 'Run'}
    </button>
    <button class="secondary" onclick={runExplain} disabled={loading || !sql.trim()}>Explain</button>
    <button class="secondary" onclick={startStream} disabled={loading || !isSingleSelect(sql)} title="Page a large read server-side via a cursor">Stream</button>
    <button class="secondary" onclick={clearEditor} disabled={loading || (!sql && !paramsText)}>Clear</button>
    <span class="hint">⌘/Ctrl + Enter · Tab to indent</span>
    <input
      class="params"
      bind:value={paramsText}
      placeholder='params (JSON array, e.g. [1, "alice"])'
      spellcheck="false"
    />
  </div>

  {#if roundTripMs != null}
    <div class="timings">
      <span class="timing">round-trip: <b>{fmt(roundTripMs)}</b></span>
      {#if ranSelect}
        <span class="timing"
          >server exec: <b>{serverMs == null ? 'n/a' : fmt(serverMs)}</b>
          <span class="via">(EXPLAIN ANALYZE)</span></span
        >
      {/if}
    </div>
  {/if}

  {#if error}
    <ErrorBox {error} />
  {/if}

  {#if planLines}
    <div class="plan">
      <div class="plan-head">Query plan <span class="via">(EXPLAIN)</span></div>
      <pre>{planLines.join('\n')}</pre>
    </div>
  {/if}

  {#if stream}
    <div class="stream-bar">
      <span class="stream-info">
        streaming · {stream.rows.length} rows loaded{stream.done ? ' · done' : ` · ~${stream.remaining} remaining`}
      </span>
      <span class="grow"></span>
      {#if !stream.done}
        <button class="secondary" onclick={loadMore} disabled={loading}>Load more</button>
      {/if}
      <button class="secondary" onclick={stopStream}>Close</button>
    </div>
    <ResultsGrid result={{ type: 'rows', columns: stream.columns, rows: stream.rows }} />
  {/if}

  {#if results}
    {#each results as result, i}
      {#if results.length > 1}
        <p class="stmt">statement {i + 1}</p>
      {/if}
      <ResultsGrid {result} />
    {/each}
  {/if}
</div>

<style>
  .editor {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }
  .session-bar {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 10px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel-alt);
    font-size: 12px;
  }
  .grow {
    flex: 1;
  }
  .sess-off {
    color: var(--muted);
  }
  .sess-on {
    color: var(--accent);
    font-weight: 600;
  }
  .sess-iso {
    color: var(--muted);
    font-family: var(--mono);
    font-size: 11px;
  }
  .iso {
    padding: 3px 6px;
    font-size: 12px;
    color: var(--text);
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 6px;
  }
  .session-bar button {
    border-radius: 6px;
    padding: 4px 10px;
    font-size: 12px;
    border: 1px solid var(--border);
    background: var(--panel);
    color: var(--text);
    cursor: pointer;
  }
  .session-bar button:disabled {
    opacity: 0.5;
  }
  .sess-begin:hover {
    border-color: var(--accent);
    color: var(--accent);
  }
  .sess-commit {
    background: var(--accent) !important;
    color: #fff !important;
    border: none !important;
  }
  .sess-rollback:hover {
    border-color: var(--err-fg);
    color: var(--err-fg);
  }
  .sess-msg {
    margin: 0;
    font-size: 12px;
    color: var(--muted);
  }
  .editor-tools {
    display: flex;
    gap: 6px;
  }
  .menu-wrap {
    position: relative;
  }
  .tool {
    background: var(--panel);
    color: var(--text);
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 4px 10px;
    font-size: 12px;
  }
  .tool:disabled {
    opacity: 0.5;
  }
  .dropdown {
    position: absolute;
    top: calc(100% + 4px);
    left: 0;
    z-index: 15;
    min-width: 260px;
    max-height: 320px;
    overflow: auto;
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 8px;
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.18);
    padding: 4px;
  }
  .drop-item {
    display: block;
    width: 100%;
    text-align: left;
    background: none;
    border: none;
    padding: 7px 9px;
    font-size: 12px;
    font-family: var(--mono);
    color: var(--text);
    border-radius: 6px;
    cursor: pointer;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
  .drop-item:hover {
    background: var(--panel-alt);
  }
  .drop-line {
    display: flex;
    align-items: center;
  }
  .drop-line .drop-item {
    flex: 1;
  }
  .drop-x {
    background: none;
    border: none;
    color: var(--muted);
    cursor: pointer;
    font-size: 11px;
    padding: 4px 8px;
  }
  .drop-x:hover {
    color: var(--err-fg);
  }
  .drop-foot {
    border-top: 1px solid var(--border);
    margin-top: 4px;
    padding-top: 4px;
    text-align: right;
  }
  .linkbtn {
    background: none;
    border: none;
    color: var(--muted);
    font-size: 11px;
    cursor: pointer;
  }
  .linkbtn:hover {
    color: var(--err-fg);
  }
  textarea {
    width: 100%;
    box-sizing: border-box;
    font-family: var(--mono);
    font-size: 13px;
    line-height: 1.5;
    padding: 10px 12px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel);
    color: var(--text);
    resize: vertical;
    tab-size: 2;
  }
  textarea:focus {
    outline: 2px solid var(--accent);
    outline-offset: -1px;
  }
  .controls {
    display: flex;
    align-items: center;
    gap: 10px;
  }
  .params {
    flex: 1;
    font-family: var(--mono);
    font-size: 12px;
    padding: 6px 10px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel);
    color: var(--text);
  }
  /* the Clear button is secondary — override the accent-filled default */
  .editor button.secondary {
    background: none;
    color: var(--text);
    border: 1px solid var(--border);
    font-weight: 500;
  }
  .hint {
    color: var(--muted);
    font-size: 12px;
  }
  .timings {
    display: flex;
    gap: 18px;
    font-size: 12px;
  }
  .timing {
    color: var(--muted);
    font-family: var(--mono);
  }
  .timing b {
    color: var(--text);
  }
  .via {
    color: var(--muted);
    opacity: 0.75;
  }
  .stmt {
    margin: 8px 0 2px;
    font-size: 12px;
    color: var(--muted);
    font-weight: 600;
  }
  .stream-bar {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 6px;
  }
  .stream-info {
    font-size: 12px;
    color: var(--muted);
    font-family: var(--mono);
  }
  .plan {
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel-alt);
    overflow: hidden;
  }
  .plan-head {
    padding: 6px 12px;
    font-size: 12px;
    font-weight: 600;
    border-bottom: 1px solid var(--border);
  }
  .plan pre {
    margin: 0;
    padding: 10px 12px;
    overflow: auto;
    font-family: var(--mono);
    font-size: 12.5px;
    line-height: 1.5;
    color: var(--text);
  }

  /* ── vector embed helper ─────────────────────────────────── */
  .tool.embed-active {
    border-color: var(--accent);
    color: var(--accent);
  }
  .embed-panel {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 8px 10px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel-alt);
    flex-wrap: wrap;
  }
  .embed-input {
    flex: 1;
    min-width: 180px;
    font-family: var(--mono);
    font-size: 12px;
    padding: 5px 9px;
    border: 1px solid var(--border);
    border-radius: 6px;
    background: var(--panel);
    color: var(--text);
  }
  .embed-input:focus {
    outline: 2px solid var(--accent);
    outline-offset: -1px;
  }
  .embed-out {
    display: flex;
    align-items: center;
    gap: 6px;
    flex: 1;
    min-width: 0;
  }
  .embed-preview {
    font-size: 11px;
    color: var(--muted);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    flex: 1;
    min-width: 0;
  }
  .embed-hint {
    font-size: 11px;
    color: var(--muted);
  }
  .embed-dims {
    font-size: 11px;
    font-weight: 600;
    color: var(--accent);
    white-space: nowrap;
  }
  .embed-dims-warn {
    color: #b45309;
  }
  .embed-tip {
    width: 100%;
    font-size: 11px;
    color: var(--muted);
    margin-top: 2px;
  }
  .embed-tip code {
    font-family: var(--mono);
    font-size: 10.5px;
    color: var(--text);
  }
  .embed-btn {
    background: none;
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--text);
    font-size: 11px;
    padding: 4px 10px;
    cursor: pointer;
    white-space: nowrap;
  }
  .embed-btn:hover {
    border-color: var(--accent);
    color: var(--accent);
  }
  .embed-btn.primary {
    background: var(--accent);
    color: #fff;
    border-color: var(--accent);
  }
  .embed-btn.primary:hover {
    opacity: 0.88;
  }
</style>
